### ISSUE TITLE
[Suggestion] Add an information tab in JEI that links to the Project Intelligence page for items

### ISSUE THREAD

**Issue by aaronhowser1** [Draconic-Inc/Draconic-Evolution#1324]
## Base information
* Minecraft version: 1.12
* Mod version: Draconic-Evolution-1.12.2-2.3.22.343-universal
* Minecraft Forge version: 14.23.5.2836

Something similar to how Actually Additions does it, like have a small snippet of information and then have a link to open the page
![image](https://user-images.githubusercontent.com/15698722/59081954-5b60b280-88b6-11e9-9ae9-14f3d67ff461.png)

**Comment by aaronhowser1** [comment]
reeeeeeeeeee

**Comment by FoxMcloud5655** [comment]
Now that Project Intelligence is a thing for 1.16.5, this suggestion is great, but should be re-opened on the appropriate GitHub repo, rather than on Draconic Evolution.
