### ISSUE TITLE
[1.16] Several Issues with Chaos guardian

### ISSUE THREAD

**Issue by DimensionalDrift1** [Draconic-Inc/Draconic-Evolution#1559]
~~Edit: I have realized immediately after posting that this has no title, oops.~~
Double Edit: you can edit titles.

## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.15.415
* Minecraft Forge version: 36.2.4
* Mod Pack: FTB Oceanblock 1.2

### Description / steps to reproduce

I have several issues with the chaos guardian, and am unsure which is/isn't intended.
-DE-related HUDs stopped working
-Chaos Guardian spams "Charged Attacks" way too often
-Laser attack does no damage
-Seems to have an absurd amount of shield
-Chaos Island doesn't explode

So I'll detail each point one by one. First, the HUD stops working. This seems to only happen WHILE fighting the Chaos Guardian. It was fine before, and immediately after the fight.
![image](https://user-images.githubusercontent.com/32022607/137006265-75a7dad7-6426-4a50-a7c0-7cc002f065a6.png)
This is what it looks like when opening the menu to configure modules.

Second, I noticed this behavior after destroying all the crystals. After completing a "Charged attack", the Guardian would more often than not, fly out to a pillar, and immediately return to the center to do another one. This feels unintended, as the gravity well attacks last a really long time.

Third, the laser attack seems to just not work. I'm not certain standing out in the open is fine, but I would always hide behind a pillar at the start, but I could just fly straight up, and despite the fact that it looked like the laser was hitting me, I wasn't taking any damage or losing any shield.

Fourth, it took me ages to destroy its shield. The health seemed to be a reasonable amount, but the large value of shield in tandem with the fact that it kept going invincible made it take a long time. I was using a Draconic Bow with a max damage of ~31, and it still took what I guess to be several hundred arrows before the shield broke. I'm not sure if I was just doing something wrong, or if it's just a really high value.

Fifth, the Chaos Island didn't explode. I don't know if it's normal, but I know that DE on earlier versions of Minecraft had the islands explode after getting the chaos shards.

I don't want to update my version of DE and do a whole other fight right now just to see if anything is already fixed, as that is going to be a general pain for the stage I'm at. 

Thank you for coming to my TED talk.

**Comment by brandon3055** [comment]
I need you to clarify something. You say the HUD stops working but then you show a screenshot of the broken module GUI with what appears to be a functioning HUD in the background. So is the HUD itself actually broken? Or is it just the GUIs? 
The broken GUI is a known issue but so far I have not figured out the exact combination of mods that cause it so I have not been able to diagnose the issue.

The guardian's attack options are fairly limited and randomly selected. But they are fairly heavily weighted in favor of "regular" attacks. A good tactic is to try to stay as close as possible to the guardian which will make it likely to activate its "defensive" attack as opposed to any other attack. Just watch out for those fireballs xD.

Also the guardian shield capacity can be adjusted via the config but it sounds like the real issue is your bow. For maximum damage, you want to prioritize velocity modules. Those have a multiplication effect on the base damage. Then throw in as many damage modules as you can to boost the base damage. Once the crystals are down I would use something like this to deal maximum some serious damage. 
![](https://ss.brandon3055.com/e3687)

Chaos island explosion has not been implemented yet.

**Comment by DimensionalDrift1** [comment]
Apologies, I did mean the GUI. I couldn't really stay close to the guardian but it did feel weird that it pretty much was invincible more than half the time. I also forgot that velocity multiplies arrow damage. It looks like you didn't address the laser thing, which to expand on, when it hit blocks it made a visual explosion, which seemed to push me back, but taking the laser directly did absolutely nothing.

**Comment by Fatsharky** [comment]
sounds like there be no way to kill him

**Comment by AlvinasLT** [comment]
Hi. I'm probably dumb, but I don't know how to kill him. This creature spawn  the Wizerds, one-shot with a beam. No matter what I do, crystals or dragon take no damage. Even in creative it is impossible to do something. I play on the modpack OceanBlock

**Comment by brandon3055** [comment]
@AlvinasLT I recommend you read the Chaos Guardian section on the DE curse page.
https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

**Comment by AlvinasLT** [comment]
Em! # This link can be temporarily disrupted by hitting the crystal with chaotic damage.# I didn’t understand where I can get chaotic damage if for this I need to kill at least 1 chaotic dragon?

**Comment by FoxMcloud5655** [comment]
The entire point of the Chaos Dragon is to be a very hard boss.  The amount of power you get from obtaining literal Chaos itself is incredible, but is completely unnecessary for most other modded play.  You don't have to do it if you can't fight it.

You also have the option of creating your own custom recipes for Chaotic gear if you simply can't do the fight.  There are a lot a good modpack out there that can provide you with the experience you're looking for, or at least be an inspiration for your own custom modpack.

**Comment by GoatRammaHamma70** [comment]
chaos guardian also no longer kills you in creative. I know its unnecessary, but I always thought it was fun to play around with and was wondering if it will in future updates.

**Comment by James103** [comment]
At the very least, would it be possible to use a config setting to limit or disable the wither storm attack (or at least the first stage thereof) that many players consider to be very annoying?

* `disableGuardianWithers` - Stops the Chaos Guardian from spawning her withers. This prevents the first stage of her wither storm attack from taking place, causing her to only do the second, third, and fourth stages.

**Comment by quietust** [comment]
It has been suggested that Mekanism makes it possible to completely neutralize the laser attack by equipping a MekaSuit helmet with an Inhalation Purification Unit installed in it, since that neutralizes all negative potion effects (and that might include "instant damage"). I haven't personally tested this myself, but a several people playing the FTB Oceanblock pack have mentioned it.

**Comment by theArhar** [comment]
> Em! # This link can be temporarily disrupted by hitting the crystal with chaotic damage.# I didn’t understand where I can get chaotic damage if for this I need to kill at least 1 chaotic dragon? And catching the blows of his laser is difficult. My opinion is that you made it too strong. It will scare off newbies. I would make a dragon of 3 levels and they would look around in color. Each could find his strength. But the stronger the dragon, the greater the reward.

Where I can find reply to this question? Crystals are invulnerable! There is literally NO wiki page for 1.16.5

**Comment by FoxMcloud5655** [comment]
But there IS a Discord for Draconic Evolution where you can find a plethera of information with one simple search for "guardian".

**Comment by theArhar** [comment]
Ok, for normal people of the Internet I will write here:
Make full MekaSuit with Inhalation Purification Unit, make wireless charging with flux controller, make poer storage with at least 3 billion RF (mekanism), tank it with no problem

**Comment by theArhar** [comment]
> If you already knew the answer to the question, then why did you ask it? Discord is the place to ask about all things related to Draconic Evolution, not GitHub issues. This is for bug reports.

First of all, found answer today hard way
Second - there is no way to find discord answers in google, and people will search there, at least I hope they can find this topic

**Comment by sbuller** [comment]
Does anyone actually enjoy this shit? This seems mostly like a way to annoy players.

**Comment by sbuller** [comment]
Oh yay! The dragon's invincible again. More waiting. Gating content beyond this slog is cruel.

**Comment by FoxMcloud5655** [comment]
I'm going to go ahead and close this.  If someone would like to bring up these topics again, please discuss them in the Brandon's Mods discord.  A convenient link for the discord server is located [here](https://discord.gg/e2HBEtF).
