### ISSUE TITLE
[1.16] Draconic Bow keeps losing modules when swapping into creative mode

### ISSUE THREAD

**Issue by e30Birdy** [Draconic-Inc/Draconic-Evolution#1583]
## Base information
Minecraft version: 1.16.5
Mod version: Draconic-Evolution-1.16.5-3.0.17.420-universal
Minecraft Forge version: 1.16.5-forge-36.2.9
Mod Pack: FTB OceanBlock

### Description / steps to reproduce

I open the menu to input modules into my bow. Once I have them all placed I close the menu and fire and everything is fine. I can reopen menu and change things or put in new upgrades. Once I swap my client over into creative mode and back the bow is empty of all modules. My Draconic chest does not have this issue and have not tested any other weapons.

It may not be doing it to the Chest because it is in the bauble slot. A friend noticed the same issue and put his stuff in a chest before swapping modes and he couldn't figure out why his modules came up missing after going back to survival mode.

**Comment by FoxMcloud5655** [comment]
This is an issue with Forge, not with Draconic Evolution.  This bug has been reported before, and there is unfortunately nothing that can be done until the Forge devs decide on what to do to best fix this.

**Comment by e30Birdy** [comment]
> This is an issue with Forge, not with Draconic Evolution. This bug has been reported before, and there is unfortunately nothing that can be done until the Forge devs decide on what to do to best fix this.

Ok makes sense. I have lost several backpacks due to this as well, now I know where the issue lies.

**Comment by FoxMcloud5655** [comment]
Try updating to the latest version of Forge.  We've had reports that 36.2.19 may work, but this requires additional testing to confirm.

**Comment by Ashley123477** [comment]
Can the warning be disabled, as it seems to notify everybody on the server that im in creative mod, i believe only OP should get this warning

**Comment by FoxMcloud5655** [comment]
While I agree, there is not currently a way to turn this off.  I highly recommend using JEI's cheat mode to give yourself items you may need.

**Comment by FoxMcloud5655** [comment]
An update to this issue; a config option has been added to turn off the warning.  I believe this issue still persists, but I am unable to confirm.

**Comment by brandon3055** [comment]
I can confirm I have fixed the issue of the message being broadcasted to everyone. That should now be impossible. 
And there is now a client-side config to disable this warning.

**Comment by VoidDave** [comment]
> I can confirm I have fixed the issue of the message being broadcasted to everyone. That should now be impossible. And there is now a client-side config to disable this warning.

Is it implementet in version 3.0.18.428? And if yes how its called bcs i cant find it in the config
