### ISSUE TITLE
[1.16] Chaos Guardian Disappearing 

### ISSUE THREAD

**Issue by SarcasticSigma** [Draconic-Inc/Draconic-Evolution#1591]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.18.428
* Minecraft Forge version: 36.2.20
* Mod Pack: All the Mods 6 v1.8.14

### Description / steps to reproduce

Using the spell Rho Aias from Mahou Tsukai to reflect the chaos guardian's projectiles back at it will sometimes cause the chaos dragon to disappear. Reloading the island (leaving and coming back) was able to cause the guardian to come back once but I couldn't get it to happen the second time.

**Comment by FoxMcloud5655** [comment]
Would be really nice to know what mod the spell came from.

**Comment by SarcasticSigma** [comment]
Sorry, could have sworn I included it. I have edited it to fix it.

**Comment by brandon3055** [comment]
Honestly not sure how this could be happening. If its reliably reproducible then I may be able to look into it at some point but in the meantime there is code in place specifically to deal which random issues like this. 

If the guardian is somehow deleted without actually dying then it should automatically get respawned after approximately 1 minute if you wait on the island.

**Comment by FoxMcloud5655** [comment]
I think this is a visual glitch, much like what's happening in issue #1682.

**Comment by FoxMcloud5655** [comment]
Seeing as how this hasn't been reproduced, it'll be closed for now.  If this is still happening in the 1.20.1 alpha of Draconic Evolution, please comment and we'll reopen this issue.
