### ISSUE TITLE
[1.16] Crash while rendering modular chest piece

### ISSUE THREAD

**Issue by longhirar** [Draconic-Inc/Draconic-Evolution#1597]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.18.428
* Minecraft Forge version: 36.2.20
* Mod Pack: Custom ![image](https://user-images.githubusercontent.com/72895064/147145358-9bc1a192-443d-4b87-ae82-3ba70cb8028f.png)

### Crash report
[hs_err_pid17624.log](https://github.com/brandon3055/Draconic-Evolution/files/7764783/hs_err_pid17624.log)
[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/7764784/latest.log)

A Crash Report was not generated.

### Description / steps to reproduce

Every time the game tries to render the modular chest piece, even if it is in JEI, creative inventory, or an ender chest.

**Comment by longhirar** [comment]
Same thing happened here:
https://github.com/brandon3055/Draconic-Evolution/issues/1528#issue-987715366

**Comment by blk6768** [comment]
My issue was a little broader than a chest piece. My game would crash when searching ANYTHING that is included in DE mod. It even crashed when using the arrows to page to DE contents without typing anything in the search bar.

**Comment by FoxMcloud5655** [comment]
Just turn off shaders in your DE config.  It's the same issue.

**Comment by blk6768** [comment]
you dont read well do you? I also stated no Optifine, nor shaders in my report..........try again

**Comment by FoxMcloud5655** [comment]
You don't read well, do you?  I said, turn off shaders in your DE config.  Not OptiFine.  This has literally nothing to do with OptiFine.

**Comment by blk6768** [comment]
I understand now, again old and not tech savvy so I apologize. Just really frustrated with it. So you are syaing I CAN use Optifine and a shaderpack, but I have to turn off the shaders in the config file? which was just done about to test.......

**Comment by blk6768** [comment]
Is there a better option to Optifine?

**Comment by FoxMcloud5655** [comment]
Magnesium/Sodium is the open-source version.  It currently works worse than OptiFine, but it IS open-source, which means that any bugs that arise can be fixed, guaranteed.  Just a matter of doing it.

**Comment by LonelySauce** [comment]
While I don't crash when rendering the chest pieces, they just don't seem to render at all for me
![2022-07-08_06 28 09](https://user-images.githubusercontent.com/23504262/177976461-de7ea406-e964-406d-bb3f-679a60dc4597.png)

![2022-07-08_06 28 11](https://user-images.githubusercontent.com/23504262/177976452-16e57944-45e6-4321-90ed-0a5a316af101.png)
![2022-07-08_06 27 40](https://user-images.githubusercontent.com/23504262/177976458-c367bb9c-2933-4743-b99a-99c8ea297933.png)

MC Version: 1.16.5
Forge Version: 36.2.34
Mod Version: 3.0.27.462
Modlist: [Underground Hideout Pack-DE Rendering Bug.zip](https://github.com/Draconic-Inc/Draconic-Evolution/files/9071348/Underground.Hideout.Pack-DE.Rendering.Bug.zip)

**Comment by FoxMcloud5655** [comment]
This is a separate issue.  Please make a new issue for it.

**Comment by FoxMcloud5655** [comment]
This issue has been fixed in later versions of Draconic Evolution.  Please update to the 1.20.1 version of Draconic Evolution.
