### ISSUE TITLE
[1.16] Chest piece doing something?

### ISSUE THREAD

**Issue by theArhar** [Draconic-Inc/Draconic-Evolution#1610]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.19.432
* Minecraft Forge version: 36.2.22
* Mod Pack: TNP Limitless 3 1.11.7

### Crash report
Not a crash

### Description / steps to reproduce

Every time I open inventory, draconic evolution chest piece starts to consume energy with sound
I show it on video:
https://youtu.be/pvT0rCGE8Kw

**Comment by FoxMcloud5655** [comment]
That's the re-equip sound, and likely is a bug with how NBT is being compared after discharging/charging.  The energy drain is from you enabling your shields.  There's a passive RF drain.

**Comment by theArhar** [comment]
Bug is still there even if I disable wireless charging, it just keep doing this sound

**Comment by FoxMcloud5655** [comment]
I didn't say that it was your fault; this is a bug that needs to be fixed.

**Comment by FoxMcloud5655** [comment]
This issue seems to have been largely taken care of and I haven't seen or heard anything about it since.  I'm going to go ahead and close this issue until further notice.  If it happens again, please let me know.
