### ISSUE TITLE
[1.16] Incompatible with Epic Fight mod on server

### ISSUE THREAD

**Issue by falcofemoralis** [Draconic-Inc/Draconic-Evolution#1611]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.19.432
* Minecraft Forge version: 36.2.22
* Mod Pack: My own

### Crash report
Not a crash

### Description / steps to reproduce

Can't install any modules (they're just invisible and don't give any effects) while using epic fight mod on server.
So, in order to reproduce it, simply install both mods: Draconic Evolution and Epic Fight in client and on server

**Comment by FoxMcloud5655** [comment]
Mod compatibility is not being considered right now.  Draconic Evolution is still in beta and must focus on its own stability before cross-mod compatibility.

Epic Fight has MANY changes that are very game breaking.  I wouldn't be surprised if this is not DE's fault and compatibility must be made on their end.

**Comment by FoxMcloud5655** [comment]
Considering that the other side has marked Draconic Evolution as incompatible, it's extremely doubtful that they are going to provide any kind of assistance.  Closing this issue until further notice.
