### ISSUE TITLE
[1.16] Chest piece has no elytra boost when put in curio slot

### ISSUE THREAD

**Issue by theArhar** [Draconic-Inc/Draconic-Evolution#1613]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.19.432
* Minecraft Forge version: 36.2.22
* Mod Pack: TNP Limitless 3 1.11.7

### Description / steps to reproduce

As described in title, there is no flight speed up on elytra flying mode when chest piece in bauble slot (on body there is)

**Comment by theArhar** [comment]
also I hope you understand that discord is not indexed by search engines, and information from there has very low value

**Comment by FoxMcloud5655** [comment]
Yes, it's not indexed.  If it was, that would be a massive violation of privacy.  GitHub issues is not the place to ask questions about Draconic Evolution; the Discord server is.  Therefore, to find answers to questions related to Draconic Evolution, it's best to search the Discord server.

Not sure why answers from another platform immediately intrinsically have a lower "value" than if it was answered elsewhere, but okay.

**Comment by FoxMcloud5655** [comment]
I know this is the original issue, but Brandon has posted more information over on #1620 about this, so I'm gonna close this one and redirect people there.
