### ISSUE TITLE
[1.16] Server crashing

### ISSUE THREAD

**Issue by vladdeda** [Draconic-Inc/Draconic-Evolution#1616]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.18.428-universal
* Minecraft Forge version: 36.2.21
* Mod Pack: Vault Hunters [https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack]

### Crash report
attached  https://pastebin.com/qE8qRshc

### Description / steps to reproduce
Build a 4x2 fusion crafting setup, placed basic crystals on each of the injectors, and 4 on a generator. Linked them up 2 injectors to one on the generator. Server crashed a moment after linking them. And crashes when a player logs in near them.

**Comment by FoxMcloud5655** [comment]
It looks like you may have your crystals in an infinite loop...  But regardless, this shouldn't crash your game.  Thanks for the bug report.

**Comment by vladdeda** [comment]
Hmmm, I don't know how.... I sat them all on the Generator, linked 2 of the injectors to one crystal each. Idk how it would have gotten an infinite loop. 0.o

**Comment by brandon3055** [comment]
Ok so after digging through the affected code this crash is actually not possible. Like this crash actually cant happen..... But evidently, it does.... sooo..... I made a change that I think should fix it?... I theoretically made this crash 'more impossible'...
It will be in the next release which should get pushed within a day or two.

**Comment by brandon3055** [comment]
I guess this is fixed?
