### ISSUE TITLE
Make Chaos Guardian fight difficult

### ISSUE THREAD

**Issue by sbuller** [Draconic-Inc/Draconic-Evolution#1617]
The current Chaos Guardian fight is simply punishing. It needs to be rethought. Extra Credits explains the difference:

https://www.youtube.com/watch?v=ea6UuRTjkKs

This is a must watch for anyone who fancies making a 'difficult' game.

**Comment by FoxMcloud5655** [comment]
As much as I like defending Brandon and accusations like these, I do slightly agree.  The gravity pulse attack which disables your flight is an awesome mechanic in my opinion, but it IS used a little excessively.  The guardian also has a LOT of damage negation and shields, and if the shields were simply halved, I think it would solve the grueling part of the battle.

With that being said, the fight isn't SUPER hard, it's mainly just time-consuming when you know what to do.

**Comment by FoxMcloud5655** [comment]
It's not like the code isn't open source, though.  If everyone agrees that the fight is too hard, then you can simply change it yourself.  Adding config options to the chances for each attack, the shield amounts, the HP, etc. would be a great pull request.

**Comment by fahlur** [comment]
From my experience with the fight. I do agree the gravity part is a little excessive. But the fight isnt punishing like shown with ExtraCredits. its difficult. If you learn the mechanics your good to go. For the laser attack go behind a wall or pillar put a bit of distance and your safe. For the gravity keep moving around the platform, if Guardian withers spawn. kill them as quick as you can, you have time but still should kill quickly to move on. Its not impossible and its not spontaneous. Its not punishing its just difficult and requires some sort of critical thinking. Now I wouldnt be against configuring options for the boss fight. But again, not punishing unless you go under geared, which is FORWARNED in the intelligence information. The chaos Guardian follows its rules to the T. So yea.

**Comment by FoxMcloud5655** [comment]
In revisiting this issue, I'll see if I can add configuration options for the fight so people can change them how they see fit.

**Comment by FoxMcloud5655** [comment]
The last time I fought the Chaos Guardian in the 1.20.1 version of Draconic Evolution, I knew the attack patterns and played it safe.  Didn't die a single time.  It's supposed to be "souls-like" in difficulty.  Maybe this could be looked at later, but for now, the issue is pretty old and no one else has really complained about it.
