### ISSUE TITLE
Error while unlinking energy crystals 1.12

### ISSUE THREAD

**Issue by Lazzil** [Draconic-Inc/Draconic-Evolution#1618]
Hello. I was using a wireless energy crystal to power a ghast farm using an industrial foregoing setup. I'm running this on the FTB Academy 1.12 pack with no other mods installed.

I have the crystal connected to my power source through a relay and used it to power the mod crusher and duplicator. I didn't like the location and decided to move it. When I tried unlinking the wireless crystal, I got an error message.

One other thing I also noticed is that the wireless crystal loses its connection when I pause the machines.
[crash-2022-01-28_16.23.01-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7962016/crash-2022-01-28_16.23.01-client.txt)

**Comment by Lazzil** [comment]
I tried editing my original post, but I guess git doesn't allow that after a while.

Just wanted to follow up and say that it's not just the IF machines that cause the issue. It works fine when I unlink everything from the wireless crystal, but the problem comes up when I try to unlink individual connections.

**Comment by FoxMcloud5655** [comment]
I do know that the connections will terminate if the machine is no longer present.  Does this hlonly happen on specific machines or mods, or is this on literally everything?

**Comment by Lazzil** [comment]
It seems to be happening sporadically on everything. On further inspection, it actually breaks when I unlink it from other crystals in addition to the machines. The error seems to only come up when I disconnect using the wireless crystal UI and doesn't happen at all with regular relays or I/O crystals.

**Comment by FoxMcloud5655** [comment]
Noted.  Try unlinking them using the wrench as a workaround, as this functionality is the only one that's present on the 1.16.5 version and works perfectly fine.

**Comment by Lazzil** [comment]
Sure, I'll do that. Thanks.

**Comment by brandon3055** [comment]
The crystal UI was more of an afterthought that never really got the polish it needed. Though I thought I ironed out most of the major issues like this... 

As for the crystals un-linking when you pause the machine. The crystals periodically check to make sure the block they are connected to is still valid and will disconnect after a while if its not. iirf pausing an IF machine temporarily removes its energy capability so its no longer a valid energy target.
There are a lot of little issues like this that I plan to fix when I re write the crystals in 1.16/1.18.
