### ISSUE TITLE
[1.16] <Adding armor related modules>

### ISSUE THREAD

**Issue by CheatEvent** [Draconic-Inc/Draconic-Evolution#1622]
For the time I tested DE on 1.16.5 I saw that shield 1)has 0 delay of taking damage 2)does not affected by any armor

So what if there was modules that 1)add delay before taking next damage on shield 2)add armor to shield (like %) 3)allow armor to affect shield (like %)?
I know that it can add some disbalance, but it can be logical (because of curios)

In addition there can be modules that 1)blocks projectiles (not DE type) 2)reflect % damage 3)add effects upon breaking shield 4)gives sertain effect (like saturation for a cost of a lot of energy)

**Comment by FoxMcloud5655** [comment]
A lot of these suggestions seem like they'd be OP.  Effects upon breaking the shield seems like a cool effect.  Many of these are better served as additions to what Draconic Evolution already offers, so if someone wants to make another mod containing these, then good on them.

I'll leave it up to Brandon on whether these should be implemented in the base mod or not, but I'm pretty sure the answer is gonna be no.

**Comment by FoxMcloud5655** [comment]
Seeing as how this issue is old now and hasn't been addressed, it seems like this is a no.  Closing the issue.
