### ISSUE TITLE
[1.12] energy crystals breaking optifine shaders

### ISSUE THREAD

**Issue by Cloud11665** [Draconic-Inc/Draconic-Evolution#1627]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.25.351
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: (if applicable) Omnifactory 1.2.2

### Crash report
(If applicable)

### Description / steps to reproduce
- load any shaders using optifine
- place/hold any energy crystal

![2022-02-19_14 44 43](https://user-images.githubusercontent.com/59028866/154803666-38c685fd-47a7-4b3d-a0dd-7a1dc9c2bc77.png)
![2022-02-19_14 44 51](https://user-images.githubusercontent.com/59028866/154803668-36d2d773-c92e-4b8c-82c8-6596d205e42a.png)

**Comment by FoxMcloud5655** [comment]
OptiFine is not supported by most mod authors.  Draconic Evolution is one of those.
