### ISSUE TITLE
[1.16] No block drop on Server

### ISSUE THREAD

**Issue by busa13** [Draconic-Inc/Draconic-Evolution#1630]
https://www.youtube.com/watch?v=C84kLRMF-0w

**Comment by FoxMcloud5655** [comment]
Video is private.

**Comment by busa13** [comment]
Open it

**Comment by brandon3055** [comment]
I am not able to reproduce this issue. The most likely cause would be a conflict with another mod or a server plugin.

**Comment by FoxMcloud5655** [comment]
If this continues to happen or someone else comes across this issue, please make another issue and repost it with as much detail as you can provide.
