### ISSUE TITLE
[Feature Request] Add more Information to the Transfer Rate of the Energy Core

### ISSUE THREAD

**Issue by TZBlockBuster** [Draconic-Inc/Draconic-Evolution#1631]
I just wanted to suggest a little feature, it would be very cool, when you hover over the Transfer Rate it shows the Current Input and Output rate so it's easier to see if Energy Production is having a problem or someone is stealing my energy again for example. Would be nice to have that.

In general awesome mod, one of the best in my opinion.

**Comment by FoxMcloud5655** [comment]
I really like this suggestion, as I've low-key wanted this since it was introduced.  I feel like it would really benefit computer interfaces too.

**Comment by brandon3055** [comment]
I was planning to do something like this when I re-wrote the core... But I was also planning to re write the core over a year ago at this point so...
![](https://ss.brandon3055.com/13182)
