### ISSUE TITLE
[1.16] Draconium Ore Not Generating (Overworld and Nether)

### ISSUE THREAD

**Issue by unsnaggedmouse2** [Draconic-Inc/Draconic-Evolution#1635]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.21.443/3.0.20.440
* Minecraft Forge version: 36.2.30
* Mod Pack: N/A

### Crash report
N/A

### Description / steps to reproduce
Draconium ore is no longer generated in the overworld or nether on the 3.0.20.440 and 3.0.21.443 versions of DE. The last version to generate ore in both dimensions was 3.0.19.432. I used Baritone to confirm the lack of generation, the end dimension however generates ore perfectly. I have confirmed config is set correctly and no mod conflicts are present as DE and its dependencies are the only mods installed (aside from Baritone).

**Comment by YarinQuapi** [comment]
Fixed in #1636

**Comment by brandon3055** [comment]
This will be fixed in the next update which I will try to release within the next few hours.
