### ISSUE TITLE
[1.16] Chaos Crystal Drops Double Shards

### ISSUE THREAD

**Issue by unsnaggedmouse2** [Draconic-Inc/Draconic-Evolution#1638]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.21.443
* Minecraft Forge version: 36.2.30
* Mod Pack: N/A

### Crash report
N/A

### Description / steps to reproduce
After defeating the Chaos Guardian, mine the chaos crystal's top part or bottom part and it will give you double the number of shards specified in the config. Mining the center gives the normal amount.

**Comment by brandon3055** [comment]
Thank you. This will be fixed in the next update.
