### ISSUE TITLE
[1.16] Armor energy gauge jumping at max value

### ISSUE THREAD

**Issue by TrodelHD** [Draconic-Inc/Draconic-Evolution#1640]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.20.440
* Minecraft Forge version: 36.2.28
* Mod Pack: All the Mods 6

### Description / steps to reproduce
If the armor has something that constantly consumes energy and it is loaded through the flux network in the inventory, then the energy gauge will jump between the max value and max value - 0.1. (e.G.: 4.0M <-> 3.9M)

**Comment by TrodelHD** [comment]
> Gonna have to give a little more clarity on what you mean by "flux network in the inventory". I'm going to guess that this is part of Flux Networks and that you can charge your inventory wirelessly with it, correct?
> 
> If that's the case, then it's a mod compatibility issue, which isn't being considered until Draconic Evolution is feature complete.

The Mod Flux Network offers a feature for wireless charging inventory slots (including armor slots).
When the chestpiece uses its energy to provide the shield, the energy meter shows MaxValue - 0.1 (e.g. 3.9M), then the flux network re-energizes it and it shows MaxValue (e.g. 4 .0M). This happens in a constant loop and is quite annoying.

**Comment by FoxMcloud5655** [comment]
Then refer to my second paragraph, if you would.

**Comment by FoxMcloud5655** [comment]
I don't think this issue needs to be closed, just that it's not a high priority.  I also don't know if it can be fixed on our side, but we won't know until we look at the code.

**Comment by brandon3055** [comment]
> My suggestion for a solution would be to also round up the energy amount. If there is 3,999,999 energy in the buffer it should not round down to 3.9M.

The problem with that (not that it matters so much in this case) is people generally intuitively know that if something says "3.9M" then they have at least that much plus some amount on top. With the nearest number rounding, it would say 4.0M until you drop below 3.95M. 

I have seen a lot of issues with things like wireless chargers interacting with my shield and tools. I think I just need to find a proper solution that fixes the underlying issue rather than a patch for this one symptom.

**Comment by SDPhantom** [comment]
I figured this wouldn't be a bug, but just how tick events work. Between Minecraft's tooltip rendering, DE consuming energy, and FluxNet replenishing it, the order of these happening is making this difference. I would assume all these happen in random order, which would be why you sometimes see 4.0M and sometimes 3.9M. This isn't the only mod affected by this. For example, AE2's wireless remote has some rendering weirdness with its RF/durability bar if you use it while it's being charged wirelessly.

**Comment by FoxMcloud5655** [comment]
This isn't a problem that can be solved simply and easily...  For now, the issue will be closed as it's not game breaking.
