### ISSUE TITLE
[1.16] Server Crash while ticking energy core

### ISSUE THREAD

**Issue by XilefTech** [Draconic-Inc/Draconic-Evolution#1641]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.20.440
* Minecraft Forge version: 36.2.20
* Mod Pack: custom

### Crash report
[(crash-report)](https://cdn.discordapp.com/attachments/691366292539572234/956278459724890222/message.txt)

### Description / steps to reproduce
I don't know wether it is reproducable, it seemed pretty random to me and only happened once. The second, I placed the energy core block, the entire server crashed. Upon restart, it crashed again with the same error message, but after a few tries of re-restarting, it somehow fixed itself again.

**Comment by brandon3055** [comment]
Looks like a very edge case issue but regardless it should be fixed in the next update.
