### ISSUE TITLE
[1.1X] <Avaritia/Misc. Module Ideas>

### ISSUE THREAD

**Issue by TheDoc989** [Draconic-Inc/Draconic-Evolution#1642]
I saw that this mod and Avaritia share owners, so I wanted to give ideas and integrations to the 2 mods.

This possibly leading to a new item tier for these "Infinity" modules, similar to the current model, with it being the most potent. Adding "Avaritia/Infinity" styled versions of the chest piece and current tools (Or at least Staff of Power)

The main concept of this is "What if the OP items in Avaritia and their abilities were combined with the layout and toggleable GUI design of DE" (Of course these would only be possible in 1.18 when Avaritia finishes updating or if it's simply decided to have them in 1.16 without the base mod) and I think the concept is pretty awesome sounding. 

**_Avaritia Modules_**

**Pickaxe Modules**

- Extreme AOE Mining (World Breaker Ability)

**Bow Modules**

- Arrow Rain Module (Longbow of the Heavens Ability)

- Infinity Arrow Damage Module

**Sword Modules**

- Infinity Damage Module

**Chest Piece Modules**

- Infinity Saturation/Auto Feeding Module

- Infinity Shield Module (No Damage, Same as the Infinity Armor)

- Infinity Undying Module

- Void Immunity Module

- Command Immunity Module

These Misc. modules are just some I thought would be cool additions to the mod, inspired by other items or enchantments from other mods

**_Misc Modules_**

**Pickaxe Modules**

- Mining Depth Module

- Auto Smelt/Fortune Module

**Bow Modules**

- Multi Arrow Module (Arrow on each horizontal and vertical side)

- Block Phasing Arrow Module

- Seeker Arrow Module (Like Archangel's Smite from ProjectE)

**Sword Module**

- Lifesteal Module

- Beheading Module

- Potion Effect Module

**Chest Piece Modules**

- Long Reach Module

- Item Storage Module (Extended Inventory. PlayerStorage Mod as reference)

**Comment by FoxMcloud5655** [comment]
Interesting, but ultimately, this needs to be an addon mod someone else makes.
