### ISSUE TITLE
[1.16] Energy Core Stabilizer "core not found" message bug

### ISSUE THREAD

**Issue by TrodelHD** [Draconic-Inc/Draconic-Evolution#1644]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.20.440
* Minecraft Forge version: 36.2.28
* Mod Pack: All the Mods 6

When you right click an "Energy Core Stabilizer" without an Energy Core near it it shows a red message "msg.de.coreNotFound.txt" in the chat. Worth noting is that my game is set to English (US) and not to german (but I am from germany). 

![image](https://user-images.githubusercontent.com/36897297/160249609-a1443816-6def-4099-9803-28f47ebe75ee.png)

**Comment by brandon3055** [comment]
This is a known issue. The energy core needs a re write so some of the old localization never got updated.

**Comment by Comins00** [comment]
Any mode to fix it? even passing by creative or smth like that?

**Comment by TrodelHD** [comment]
> Any mode to fix it? even passing by creative or smth like that?

What do you mean with "Any mode to fix it"?
It's just a display/message bug not a functional one.
