### ISSUE TITLE
[1.16.5] Server players cannot open the Tools module. But op can

### ISSUE THREAD

**Issue by 764069075** [Draconic-Inc/Draconic-Evolution#1645]
## Base information
* Minecraft version:1.16.5
* Mod version:1.16.5-3.0.22.444-universal
* Minecraft Forge version:36.2.28
* Mod Pack: (if applicable)

### Crash report
(If applicable)
no crash
### Description / steps to reproduce
Server players can not open the tools module, but administrators can, if the administrator removed their administrative privileges, will also not be able to open, use the shortcut keys after this interface flash disappeared, there is no error message, but in the single-player mode can open the tools template. In addition, according to the configuration interface can be used normally, once you click the button to open the tools module will also appear the same situation, the interface flashes a little did not disappear, as if the interface has not been used.

**Comment by brandon3055** [comment]
If your running the latest BrandonsCore try setting `clientPermissionVerification` to false in the BCore config.
