### ISSUE TITLE
[1.16] Chaos guardian Laser

### ISSUE THREAD

**Issue by TiVO-OP** [Draconic-Inc/Draconic-Evolution#1647]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.22.444
* Minecraft Forge version: 36.2.33
* Mod Pack: OceanBlock

### Description / steps to reproduce

Chaos guardian spams the Laser beam attack and there's no way to dodge it, except going out of his range. This attack drains all of my shields in  half a second and attacks me as soon as I'm  near the chaos guardian. No way to kill him in survival mode, also tested on 2 chaos guardians both do the same thing.

**Comment by brandon3055** [comment]
No you cant dodge it. When you hear the laser attack charging you need to hide behind one of the obsidian pillars and wait it out.
I recommend you use a combination of elytra and creative flight. Ideally you should be using a Draconic flight module.
