### ISSUE TITLE
[1.16.5] Crash When using Crystal Binder

### ISSUE THREAD

**Issue by CodWafer** [Draconic-Inc/Draconic-Evolution#1649]
I used a crystal binder on a basic energy relay, and it crashed my game.
[crash-2022-04-07_12.18.45-client.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8445914/crash-2022-04-07_12.18.45-client.txt)
Latest version of DE and Brandons Core.

**Comment by brandon3055** [comment]
Was this a one off crash or is it reproducible.
