### ISSUE TITLE
[1.16.5] crash

### ISSUE THREAD

**Issue by Evofy** [Draconic-Inc/Draconic-Evolution#1651]
I play modpack 1.16.5 with Draconic-Evolution and all of a sudden meinkraft can close.
Crash log I can not understand but to https://pastebin.com/e3rbvwGQ

**Comment by FoxMcloud5655** [comment]
First of all, don't use OptiFine.  It messes with code and we don't know what it does, so we can't code around its hacks.  Secondly, dedicate more RAM.  You need about 6 GB with the mods you're running.  Finally, disable shaders in Draconic Evolution's config.  Your GPU isn't good enough to handle them (we've seen many more issues with AMD GPU's).
