### ISSUE TITLE
Can't respawn after used /kill command wearing chaotic armor

### ISSUE THREAD

**Issue by Ronald0410** [Draconic-Inc/Draconic-Evolution#1654]
After I  used "/kill" command while wearing chaotic armor it said in the chat that I was struck down by an unsurvivable force, then I went into a "ghost" mode where I can't do anything, can't open chests, can't use any items, can't break anything, etc. 

The language file for Draconic Evolution has this:
death.attack.administrative.kill=%1$s was struck down by an unsurvivable force

Are there any ways to go out of this "ghost" mode?

**Comment by FoxMcloud5655** [comment]
Interesting...  The closest thing I can think of is to take off your Chaotic Chestpiece and kill yourself again.  If you're unable to do that, try killing yourself several times until you run out of protections.  We'll have to look into this further.

**Comment by FoxMcloud5655** [comment]
Can you upload your player here?  You can find it in single-player as `level.dat` and in multiplayer as your UUID under the `playerdata` folder.

**Comment by brandon3055** [comment]
Closed because no response from OP
