### ISSUE TITLE
[1.16] Chaos Island crashing the client when rendered

### ISSUE THREAD

**Issue by Em4an3el** [Draconic-Inc/Draconic-Evolution#1655]
## Base information
* Minecraft version: 1.16.5
* Mod version:  3.0.22.444
* Minecraft Forge version: 36.2.34
* Mod Pack: https://pastebin.com/e0E1u59y download : https://mega.nz/file/lJdQjByY#eQlFIcr-APwXw5s5G21SxoexyEdZJiCRhbriM4zzphs

### Crash report
https://pastebin.com/ehr9eDt9

### Description / steps to reproduce
fly in the end until you find a chaos island or teleport to it
reset end region files "worked fine before i've reseted mine"

info: not all the chaos islands may crash your game

**Comment by brandon3055** [comment]
This should be fixed in the next version.
