### ISSUE TITLE
[1.16] "Stabilizers Invalid" when attempting to create Energy Core.

### ISSUE THREAD

**Issue by Xitenic** [Draconic-Inc/Draconic-Evolution#1657]
* Minecraft version: 1.16.4
* Mod version: 1.16.5
* Minecraft Forge version: 1.16.4 - 36.6.22
* Mod Pack: Direwolf20 1.16
* ProjectIntelligence 1.16.5
* Draconic Evolution 1.16.5

Added the latest Draconic Evolution (that is compatible) into Direwolf20 1.16 modpack. Unable to create an Energy Core with differing layouts in either Singleplayer or Creative. Error is persistent; "Stabilizers Invalid".
Screenshots here of various attempts:
[Setup 1#:](https://imgur.com/a/8GNtJ9Y)
[Setup 2#:](https://imgur.com/a/gDjDW85)
[Screenshot of error:](https://imgur.com/a/NphO81b)
[Second attempt at setup, and following error](https://imgur.com/a/SVH4VnH)

Created a Reddit post of the above issue, and have not been able to find any solution. Can be found [here.](https://www.reddit.com/r/feedthebeast/comments/ul7942/draconic_evolution_energy_core_stabilizers_invalid/)

**Comment by Xitenic** [comment]
Update:
Multi-block Energy Core works in a Creative world when exited and restarted, leading me to think that adding Draconic Evolution to a server with Direwolf20 1.16 instance installed, which does not have Draconic Evolution pre-installed, may mess things up for the world. - Possible configuration issue?

**Comment by FoxMcloud5655** [comment]
You did not provide the version of Draconic Evolution you were actually using.  Regardless, this is a known issue and has already been fixed in the latest version.  Go update, and you'll find that it works properly again.
