### ISSUE TITLE
[1.16] Mob grinder crashes when interacted with in Brandon's Core 247

### ISSUE THREAD

**Issue by Sly0511** [Draconic-Inc/Draconic-Evolution#1658]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.22.444
* Minecraft Forge version: 36.2.34
* Mod Pack: (if applicable)

### Crash report
[crash-2022-05-24_12.40.38-client.txt](https://pastebin.com/kVn3D2Ah)

### Description / steps to repro
Get Brandon's Core 247
Get DE Version mentioned above
Interact with a Mob Grinder
(Doesn't happen on 244)

**Comment by brandon3055** [comment]
Update Draconic Evolution.

**Comment by Sly0511** [comment]
Still happens but with generator

**Comment by brandon3055** [comment]
Please post a new crash report

**Comment by Sly0511** [comment]
[Crash Report](https://pastebin.com/966mLscp)
Note that in this one I've disabled mouse tweaks which I was told to be causing issues

**Comment by Sly0511** [comment]
[crash-2022-05-25_21.47.45-server.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8777620/crash-2022-05-25_21.47.45-server.txt)
[crash-2022-05-26_06.30.59-server.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8777621/crash-2022-05-26_06.30.59-server.txt)
[crash-2022-05-25_21.45.45-server.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8777622/crash-2022-05-25_21.45.45-server.txt)
There's 3 more here from yesterday and today

**Comment by Sly0511** [comment]
[crash-2022-05-26_09.43.20-client.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8777651/crash-2022-05-26_09.43.20-client.txt)
I have no clue if this is related but it had a ton of DE mentioned in it

**Comment by FoxMcloud5655** [comment]
Please make sure you're posting these crashes with OptiFine disabled!  It has been known to cause major problems with some mods, including Draconic Evolution.

**Comment by brandon3055** [comment]
Mouse tweaks is not the issue. Its just a symptom. The real issue is you need to update Draconic Evolution. Please ***Actually*** update Draconic Evolution and try again.

**Comment by Sly0511** [comment]
Now you see CurseForge won't pop the update for me...for some reason, I'll download manually, thought I was up to date because of that

**Comment by SirOMGitsYOU** [comment]
Also experiencing this issue and am on the latest version of DE
[crash-2022-05-26_05.58.40-server.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8778146/crash-2022-05-26_05.58.40-server.txt)

**Comment by covers1624** [comment]
That is absolutely not the same issue.

Please do not hijack issues.

Please create a new issue for this following the bug reporting form.
