### ISSUE TITLE
[1.16] Crash when Using JEI search

### ISSUE THREAD

**Issue by blk6768** [Draconic-Inc/Draconic-Evolution#1660]
## Base information
* Minecraft version:
* Mod version:
* Minecraft Forge version:
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce

I have tried playing 116.5 with DE but I keep having issues when searching for different things using JEI. On very first run everything is fine but when I reload my world afterwards I start having crash issues while searching. I've gone to the extent of using DE and JEI as my only 2 mods in the world and have same issue. Once I remove DE completely the problem goes away as well indicating it is something with DE itself.

**Comment by FoxMcloud5655** [comment]
Remove OptiFine.  You also didn't provide a crash report, your mod version, or any other information, so this issue is being insta-closed.

**Comment by FoxMcloud5655** [comment]
If you don't use OptiFine like most people that have this issue do, then disable shaders in Draconic Evolution's config.
