### ISSUE TITLE
[1.16] Bug with upgrades.

### ISSUE THREAD

**Issue by Seventty7** [Draconic-Inc/Draconic-Evolution#1661]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.25.456
* Minecraft Forge version: 36.2.33
* Mod Pack: (if applicable) - 

### Crash report
 - 
### Description / steps to reproduce

When I open the module menu and insert upgrades, they just disappear, but they have an effect. When I open any interface, the effect disappears, but the upgrades remain invisible and you can get them. The promblem appears only on server, in solo game its okay :/

**Comment by brandon3055** [comment]
If you are using the "Epic Fight" mod this is a know issue. I just have not had a chance to debug the issue. They could be doing something dumb or it could be on my end.

**Comment by Seventty7** [comment]
> 

yeah, im using it, ill try to delete it and come back

**Comment by Seventty7** [comment]
Yeah. The problem was Epic Fight. thx
