### ISSUE TITLE
Draconic evolution crashes my game 

### ISSUE THREAD

**Issue by Pplover123** [Draconic-Inc/Draconic-Evolution#1662]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
* Minecraft Forge version:14.23.5.2859
* Mod Pack: 
* Crash report:- https://pastebin.com/0WkfRQFy

My minecraft crashed after I created the energy relay and since then it crashes whenever I load my world. Please help cause I spent 3 months in that world and don't want to delete it

**Comment by FoxMcloud5655** [comment]
Turn off shaders in your config.  The 1.12.2 version of Draconic Evolution is no longer being developed.

**Comment by brandon3055** [comment]
Shaders are not android.

**Comment by FoxMcloud5655** [comment]
Somehow I missed that they were running on Android 12.

**Comment by brandon3055** [comment]
> Somehow I missed that they were running on Android 12.

The hint was 1.12. Shaders dont normally _usually_ crash in 1.12 so i checked the system details.
