### ISSUE TITLE
[1.16] All recipes Missing in latest version

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Draconic-Inc/Draconic-Evolution#1664]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.26.459
* Minecraft Forge version: 36.2.35
* Mod Pack: (if applicable) https://www.curseforge.com/minecraft/modpacks/aboe-3

### Crash report
(If applicable)
n/a
### Description / steps to reproduce

the issue with missing recipes only ever occurs when playing on a server does not affect singleplayer, I can provide client and server logs if needed.

This removes all recipes from the game for some reason including vanilla recipes

**Comment by FoxMcloud5655** [comment]
Sounds like that's a modpack issue.  If they have conflicting recipes, clear them out using CraftTweaker or another equivalent, or if there's a mod conflict of some sort, that can also cause this.

Please feel free to reply if this is not the case, and I'll reopen this issue.

**Comment by SirOMGitsYOU** [comment]
> using CraftTweaker or another equivalent, or if there's a mod conflict of some sort, that can also cause this.

Hi, can confirm we try to have little to no conflicting recipes in our modpack, from what I've experienced this has happened once before (completely out of our control) with Thermal series mods, which revert to a specific version and fixed it until they released a fix on their side for this.

that was a long while ago and is all fixed up, the issue here I can revert literally 1 version down on DE and it fixes the issue no problemo, but we need the latest version as yous implemented a fix for an issue we were having where the grinder completely crashes out the server when used.

**Comment by FoxMcloud5655** [comment]
I see.  Well, until this is resolved or confirmed working elsewhere, I'll reopen the issue and let Brandon know.

**Comment by brandon3055** [comment]
Absolutely nothing i did between those versions has anything to do with recipes.....
Only thing i can think of is maybe you got a corrupt jar or the jar didn't build properly. Though a bad build seems unlikely. I would have expected to hear about that a lot sooner. Maybe try a fresh build.
https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.26.460/Draconic-Evolution-1.16.5-3.0.26.460-universal.jar

**Comment by SirOMGitsYOU** [comment]
Thanks for this Brandon, I did some further tests now I've finished work and it looked like it was some really weird interaction of a specific version of blood magic that was updated and the latest version of DE causing some weird funkiness for me,  I've now resolved it by updating blood magic again so it must have been something on their end, So sorry for the confusion caused it was very odd behaviour
