### ISSUE TITLE
[1.16] <Title>Crash when using JEI search

### ISSUE THREAD

**Issue by blk6768** [Draconic-Inc/Draconic-Evolution#1665]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.026459
* Minecraft Forge version:36.2.35
* Mod Pack: (if applicable) FTB Direwolf20

### Crash report
(If applicable)

[hs_err_pid7184.log](https://github.com/Draconic-Inc/Draconic-Evolution/files/8923299/hs_err_pid7184.log)

[crash-2022-06-13_17.53.55-client.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/8923305/crash-2022-06-13_17.53.55-client.txt)

**Comment by FoxMcloud5655** [comment]
Duplicate of #1597.
