### ISSUE TITLE
[1.16] Redstone Mode on Draconic Reactor doesn't work

### ISSUE THREAD

**Issue by Kitsune-Ultima** [Draconic-Inc/Draconic-Evolution#1669]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.26.459
* Minecraft Forge version: 36.2.33
* Mod Pack: (none)

### Crash report
(not a crash)

### Description / steps to reproduce

I was testing the draconic reactor in a creative world when I discovered that upon attempting to change the redstone mode that it was stuck on "Temp" or at least showed no visible change. No other mods were present other than curios
gif i made to showcase this -> https://i.imgur.com/UIZFY9u.gif

**Comment by FoxMcloud5655** [comment]
Duplicate of Draconic-Inc/BrandonsCore#99
