### ISSUE TITLE
Minor Issue with Energy core

### ISSUE THREAD

**Issue by DayOfHeat** [Draconic-Inc/Draconic-Evolution#1670]
When using the energy core, if the time to fill is in the 1 day mark, it says "1 days" and x hours as opposed to "1 day". This is a minor issue, but it would be nice to see it fixed in a future build. This is in 1.12 ATM3 for reference.

**Comment by FoxMcloud5655** [comment]
Ah yes, the infamous "spelling" mistakes of brandon3055, which totally doesn't exist.

Should be a simple fix :P
