### ISSUE TITLE
Ps Komuk_Hapkomuk

### ISSUE THREAD

**Issue by Komuk-Hapkomuk** [Draconic-Inc/Draconic-Evolution#1674]
Hello dear developers, I would like to ask a few questions that interest me. 
1. When approximately can we expect the long-awaited full version of the mod for 1.16.5? 
2. Is it possible to expect a mod for 1.18 or more soon?

**Comment by FoxMcloud5655** [comment]
The issues section of GitHub is not a place to ask questions.  If you want to do that, please do so in the Discord server instead: https://discord.gg/e2HBEtF
