### ISSUE TITLE
[Feature Request] More config options for spawners

### ISSUE THREAD

**Issue by MiniRaptor** [Draconic-Inc/Draconic-Evolution#1675]
Hello, I'm playing with the galactic craft mod, and I recently ran into a problem. I have a space station that counts as a game as another dimension. And because of this, my spawners do not work on the space station, and this gives me a significant inconvenience. A huge request to the author to add a finer settings of spawners in the mod config. So that you can also configure biomes and dimensions for spawners. And the rest I want to say thanks to the author for this gorgeous mod.

**Comment by FoxMcloud5655** [comment]
The spawners don't care what DIM they're in...  It may be something to do with Galacticraft.  If you're still having this issue, please let me know and I'll reopen this if needed.

Try using Beyond Earth instead since that version is on CurseForge and can be included in modpacks easily.
