### ISSUE TITLE
[1.16] not loading correctly

### ISSUE THREAD

**Issue by lilrajoo** [Draconic-Inc/Draconic-Evolution#1676]
## Base information
* Minecraft version:1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.27.462-universal.jar
* Minecraft Forge version: forge 36.2.33[none of the ver work]
* Mod Pack: own

### Crash report
https://pastebin.com/q5WAJ9aN

**Comment by FoxMcloud5655** [comment]
Not only is Draconic Evolution not mentioned anywhere in this crash, but this isn't even a crash related to Brandon's Core, which is what I assume this was posted for.

Your crash is coming from Random Patches.

**Comment by lilrajoo** [comment]
sry for not giving info correctly and thx 👍
