### ISSUE TITLE
Flux capacitors do not update when wirelessly charged.

### ISSUE THREAD

**Issue by O3nboi** [Draconic-Inc/Draconic-Evolution#1677]
I have flux networks wireless charging in my world, and this makes me practically invincible as my armour tanks any lethal damage and gets immediately charged by my flux capacitors. However, when using power-guzzling draconic weapons, like the draconic bow, the capacitors' values go down, and don't charge until i update one of them in my inventory.
Here is a video demonstration:
https://youtu.be/T91dtSVpYKY
I do not know if it exists within other versions, but I have found it exists in 1.10.2.

**Comment by FoxMcloud5655** [comment]
Minecraft 1.10.2 isn't supported.
