### ISSUE TITLE
[1.16.5] Draconic Reactor not working

### ISSUE THREAD

**Issue by TheOmegaSystem** [Draconic-Inc/Draconic-Evolution#1678]
Hello, I have put every number i can possibly think of into the flux gates for it to be stable and its not working at all, using latest draconic evo for 1.16.5, i have been trying to get it to work for 3 days, it either explodes instantly or shuts down due to too high energy saturation, what the hell?

**Comment by FoxMcloud5655** [comment]
Is this issue still happening?  It's been working fine for everyone else.  If you're not able to get it to work, please comment here again and I'll reopen the issue if it's a bug.
