### ISSUE TITLE
1.10.2 reactor issue (idk if im supposed to be using this so sorry if im not)

### ISSUE THREAD

**Issue by Spjt2420** [Draconic-Inc/Draconic-Evolution#1679]
when ever i make a reactor it just blows up right away no matter how much power i put in

**Comment by FoxMcloud5655** [comment]
Put power in, take nothing out.  You won't blow up.

**Comment by Spjt2420** [comment]
i did do that with one of them it still blew up

**Comment by Spjt2420** [comment]
i figured it out
