### ISSUE TITLE
[1.16.5] Particle Generator not working

### ISSUE THREAD

**Issue by TheTrueVirus** [Draconic-Inc/Draconic-Evolution#1683]
Tried to use the particle generator as its own block for generating particle. Placing block, right click and shift right click not working. Just a block with no function currently.
Using:
- Minecraft 1.16.5
- Forge 36.2.39
- Mod-Version 3.0.27.462-universal
- BrandonsCore Version 3.0.15.248-universal

All togehter with 111 other mods.

**Comment by FoxMcloud5655** [comment]
It's still a WIP.

**Comment by TheTrueVirus** [comment]
But the Particle Generator worked in earlier versions. Why not in the 1.16.5?

**Comment by FoxMcloud5655** [comment]
Again, because it's a WIP.  Just like the Celestial Manipulator isn't in the 1.16.5 version.  Draconic Evolution 3 for 1.16.5 is in beta still, and not everything works.  The particle generator is there strictly as a crafting ingredient for the Energy Core Stabilizers.
