### ISSUE TITLE
[1.16] Dislocator Display coordinates incorrect

### ISSUE THREAD

**Issue by MissionArcher** [Draconic-Inc/Draconic-Evolution#1687]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.27.462-universal
* Minecraft Forge version: 36.2.39
* Mod Pack: N/A

### Description / steps to reproduce
I'm sure this is a known issue, but I don't see it in the open issues tab
Set a waypoint in the Advanced Dislocator
Read the coordinates
The Z coordinate displays a duplicate of the Y coordinate
This does not effect the functionality of the teleportation, just gives me difficulty telling which Chaos Dragon each of my waypoints lead to when talking with my friends that have differently named waypoints

**Comment by brandon3055** [comment]
This was fixed a while ago. Seems I forgot to close the issue.
