### ISSUE TITLE
OP energy is not good

### ISSUE THREAD

**Issue by tikcuton2461** [Draconic-Inc/Draconic-Evolution#1688]
Minecraft version: 1 16 5
Please return the FE or RF energy, OP energy not good

**Comment by brandon3055** [comment]
RF no longer exists. OP is an extension of FE meaning it is fully compatible with FE.

**Comment by FoxMcloud5655** [comment]
Another thing; FE is limited in its transfer rate and storage to around 2.14 trillion RF.  OP, on the other hand, is way, WAY more than that.
