### ISSUE TITLE
[1.16] One or more injectors are too close

### ISSUE THREAD

**Issue by Ylous** [Draconic-Inc/Draconic-Evolution#1690]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.27.462
* Minecraft Forge version: 36.2.39
* Mod Pack: N/A

### Description / steps to reproduce
**Step 1**: Start Minecraft
**Step 2:** Join in the world
**Step 3**: Build Fusion Crafting construction
**Step 4**: Right-Click to Fusion Crafting Core

***Result***: One or more injectors are too close!

**Comment by brandon3055** [comment]
You need at least 2 blocks between the core and the injectors. 
Also the error message in the GUI won't go away until you place something on one of the injectors.
That is a minor bug.

**Comment by Ylous** [comment]
> You need at least 2 blocks between the core and the injectors. Also the error message in the GUI won't go away until you place something on one of the injectors. That is a minor bug.

![2022-10-21_18 13 19](https://user-images.githubusercontent.com/60031693/197229569-265705d3-ef1c-4790-b8d5-2c2a6c53668d.png)
