### ISSUE TITLE
[1.16] Draconic Weapons,Tools, and chest piece invisible

### ISSUE THREAD

**Issue by khaos99X** [Draconic-Inc/Draconic-Evolution#1692]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.27.462
* Minecraft Forge version: 36.2.39
* Mod Pack: (if applicable) Age of Fate

### Description / steps to reproduce
1.Load into game
2. Wait few minutes while items show up then after about 5 minutes they just turn invisible

[latest.log](https://github.com/Draconic-Inc/Draconic-Evolution/files/9905521/latest.log)
![2022-10-31_17 44 58](https://user-images.githubusercontent.com/116288372/199126059-d02c71a5-ad6f-4465-827b-a0b8f1fc326d.png)
![2022-10-31_17 53 05](https://user-images.githubusercontent.com/116288372/199126061-e6e73b62-d8ed-4de6-b786-e4b14e16255e.png)

The two screenshots are from the same session trying to show what I am talking about somewhat better as it is strange interaction as it also does it in the Quest book included with modpack.

**Comment by FoxMcloud5655** [comment]
Don't use Optifine.
