### ISSUE TITLE
[1.16] <Title> Visual bug - Tools & Armor

### ISSUE THREAD

**Issue by JVortex02** [Draconic-Inc/Draconic-Evolution#1694]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.27.462
* Minecraft Forge version: forge-1.16.5-36.2.35
* Mod Pack: A bit of everything 3

### Description / steps to reproduce
When ingame and I pick any tool or armor (for example Chaotic Pickaxe) it only shows it in my Inventory and in my POV.
But if another player looks at me the tools are invisible. In addition to that if I drop the tool on the ground it becomes invisible. 
Please Help!

![2022-11-03_13 03 20](https://user-images.githubusercontent.com/117360138/199716049-3bffce50-26ab-465d-ae75-b21c600b62b4.png)
![2022-11-03_13 03 22](https://user-images.githubusercontent.com/117360138/199716053-d3f38a48-5396-462a-a0f7-45a40979a37b.png)
![2022-11-03_13 03 05](https://user-images.githubusercontent.com/117360138/199716060-e598fcc4-cd47-48e4-aad5-faf61eb70013.png)
![2022-11-03_13 03 12](https://user-images.githubusercontent.com/117360138/199716066-36eb144b-e840-4098-b4f5-7669deef6edb.png)

These are the screenshots where you can see my issue.

**Comment by FoxMcloud5655** [comment]
Interesting.  The 1.16.5 version may not be updated with fixes since we've been focused on 1.18.2 for now, but if it gets revisited, then this will get a look-see.

**Comment by iAmAutolocker** [comment]
I am 100% certain that this is caused by Oculus. Perhaps the shaders on the weapons and shield are not loaded properly when Oculus is installed.

**Comment by FoxMcloud5655** [comment]
If there's another mod loading shaders on top of the shaders that Draconic Evolution uses, that can certainly mess it up.

**Comment by FoxMcloud5655** [comment]
Seeing as how this is an old issue and it's a mod conflict issue that was already solved in later versions of Minecraft, this issue will now be closed.
