### ISSUE TITLE
[1.16] <Mods failed to load>

### ISSUE THREAD

**Issue by Ant-bytes** [Draconic-Inc/Draconic-Evolution#1695]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.27.462
* Minecraft Forge version: forge-1.16.5-36.2.39
* Mod Pack: Crazy Craft Updated

### Crash report
https://pastebin.com/01aYn6Jb

### Description / steps to reproduce
I copied all the mods and configs from the modpack folder and pasted them into my minecraft directory (along side a few other performance mods.) When I tried launching the game, it gave me this error.

**Comment by brandon3055** [comment]
Remove the "few other performance mods". Then if the game launches add them back one at a time until it breaks.
This is not a DE issue. It looks like something in your pack is breaking mixins which seems to be affecting several mods in your pack.

**Comment by Ant-bytes** [comment]
> Remove the "few other performance mods". Then if the game launches add them back one at a time until it breaks. This is not a DE issue. It looks like something in your pack is breaking mixins which seems to be affecting several mods in your pack.

Well, it worked, but it also didn't?

Now I'm getting this error: https://pastebin.com/85HyzArk

**Comment by FoxMcloud5655** [comment]
You have invalid configs, specifically `dungeons_enhanced-common.toml`.  Delete the config and try again.  Also, the crash report shouldn't be that hard to read; just look for whatever's at the top!
