### ISSUE TITLE
[1.16] <Title> rubidium mod bug

### ISSUE THREAD

**Issue by Dragonfire75** [Draconic-Inc/Draconic-Evolution#1699]
Draconic-Evolution sword hide

**Comment by Dragonfire75** [comment]
https://drive.google.com/file/d/1geV0Q9mCjeilYqAryg5fwOjO-59GDV5t/view?usp=share_link

**Comment by FoxMcloud5655** [comment]
Unfortunately, that law gives us nothing about the actual issue.  I'm going to have to close this until more info is found.

**Comment by Dragonfire75** [comment]
sorry
