### ISSUE TITLE
[1.16] No TechLevel in API

### ISSUE THREAD

**Issue by SirZontax** [Draconic-Inc/Draconic-Evolution#1700]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.28.500
* Minecraft Forge version: 1.16.5-36.2.0
* Mod Pack: none

### Crash report
none

### Description / steps to reproduce
Tried to implement features with your mod via FusionRecipe. One requiered argument is TechLevel from `com.brandon3055.draconicevolution.api.TechLevel` but it doesn't exist which is wierd because it is clearly needed for a FusionRecipe, even in your newest GitHub-Version.

**Comment by SirZontax** [comment]
Fixed: You need the BrandonsCore-API, not only DE-API, so its `com.brandon3055.brandonscore.api.TechLevel`

**Comment by FoxMcloud5655** [comment]
Fusion Crafting was basically directly ported to simply enable it's functionality.  The 1.16.5 version of Draconic Evolution is still in beta, so these things are to be expected.

That being said, I'll make sure that @brandon3055  knows about this.
