### ISSUE TITLE
[1.12] game keeps crashing

### ISSUE THREAD

**Issue by nzxtpxnda** [Draconic-Inc/Draconic-Evolution#1703]
## Base information
* Minecraft version: 1.12.2
* Mod version:
* Minecraft Forge version: 14.23.4.2718
* Mod Pack: (if applicable) Ragnamod 4 tried to add draconicaddons

### Crash report
https://pastebin.com/7dzCfNAk

**Comment by FoxMcloud5655** [comment]
This is not a Draconic Evolution issue.  Please open an issue with Draconic Additions.
