### ISSUE TITLE
[1.16] modules disappear from gear <in survival>

### ISSUE THREAD

**Issue by FelixDaemonWox** [Draconic-Inc/Draconic-Evolution#1704]
* Minecraft version: 1.16.5
* Mod version: 3.0.26.459
* Minecraft Forge version: 36.2.39
* Mod Pack: Custom

### Description / steps to reproduce
D.E. items lose all modules in a hard to predict way. in survival.

I'm aware that going into creative mode will trigger this (and that there was another issue regarding this on creative), however this is happening to me in a completely survival world.

the only mods I have that add curios or could interact with D.E. items are Mekanism, Thermal Expansion, Immersive Engineering and Botania, however while this happened no curios or items that could interact with D.E. where in my inventory

behavior I have observed so far:
Chest piece will lose modules when:
* placed in a charging port in any machinery
* when changing slot in vanilla inventory (or moving it in general) sometimes but not often
- so far the chest piece is stable in the curio slot and it's the most stable of the mod
- has no problem being charged with the charge pad from Mekanism

Capacitor will lose modules when:
* placed in a charging port in any machinery
* when changing slot in vanilla inventory (or moving it in general) sometimes
* if it's stored energy reaches 0 (always)
* set to charge inventory (sometimes)
- so far the chest piece is stable in the curio slot as long as it's charge is above 0
- has no problem being charged with the charge pad from Mekanism

Tools will lose modules when:
* when changing slot in vanilla inventory (or moving it in general) very often, like every second time I move them 
* just out of nowhere, after sitting in the vanilla inventory for a while fully charged without being interacted with
* when stepping on a Mekanism charge pad

**Comment by brandon3055** [comment]
I am not able to reproduce this with the mod list you have provided. 
![](https://ss.brandon3055.com/c6b22)
Could you please include the versions of all the mods you are using.
A screenshot of your mods folder should be all I need.

**Comment by FelixDaemonWox** [comment]
hmmm
is a moded server with pluggins
![image](https://user-images.githubusercontent.com/57429817/213858637-274e1f1d-b147-44a6-bf41-eb16a69df70d.png)
only plugins are essentials x, sleep-most and skin restorer

here's the mod list:
https://pastebin.com/FWEd6HD6

**Comment by brandon3055** [comment]
Oh. I misunderstood. I thought you meant `Mekanism, Thermal Expansion, Immersive Engineering and Botania` were the only mods you had installed. 
I need to know what mod or plugin is causing the issue before I can debug it. Realistically it could be caused by any mod in your pack but most likely a mod that somehow affects items in your inventory.  

From the description of your issue, it sounds like something is clearing the capability data server side. Moving the item in your inventory would then sync those changes to your client.

If you are able to do some debugging (If this is your server) you could start by disabling your plugins. If it's not that try a fresh world. It could be something you have placed like a wireless charger.
if it's still happening you don't have many more options beyond simply removing mods until the issue goes away.

**Comment by FoxMcloud5655** [comment]
I don't think simply disabling the plugins will work.  The only way you can get plugins and mods to work together is by using an unofficial hybrid server, and that causes issues exactly like this.  Plugins are only designed for vanilla, and capabilities in the way that is implemented in Draconic Evolution simply isn't ever a consideration for these kinds of plugins, especially EssentialsX.

Try doing what you're doing on a normal Forge server, then see if that fixes it.  There are many mods that emulate the functions of those plugins you can use, most of them from FTB.

**Comment by FelixDaemonWox** [comment]
Oh, ok, I'll try removing the plugins and make some test with a Forge server.

**Comment by FoxMcloud5655** [comment]
Didn't even see you added a screenshot of Mohist.  Of all the server hybrids, that one has been known to install plugins for you without telling you they're unofficial versions made by them.

People (not saying this is you) that "need" plugins for their server tend to ignore all requests to even attempt running a pure Forge server with equivalent mods to their plugins.  If you absolutely MUST use a very buggy server that can and will cause issues, then I suggest using a different one, like Magma.  I do not endorse them or recommend them either, but it's better than having plugins replaced on you by whatever code they wanted to download to your server.

**Comment by FoxMcloud5655** [comment]
> Oh, ok, I'll try removing the plugins and make some test with a Forge server.

❤️

**Comment by FelixDaemonWox** [comment]
Alright, so I made some tests, it was indeed Mohist's fault

I took out all plugins, and ran the server with Mohist, the problem persisted

I tried runing the server with:
* Sponge: couldn't start
* Magma: starts well but throws *package too big* when trying to enter
* Forge: couldn't get it to read the "mods" folder

I then started the server in Magma on a fresh world with all the plugins (EssentialX, sleepmost, skinrestorer), with only Draconic Evolution and the Mekanism mod series (Mk, Mk tools, Mk generators & Mk addons)

After this the problem was gone, I then tried the same setup with Mohist and the problem came back


> Didn't even see you added a screenshot of Mohist
Yes, I've seen some posts that Mohist isn't the best server, but when I created the server (and even now) is was the only server that seems to work well.

**Comment by FoxMcloud5655** [comment]
Glad to know it's not DE's fault.  Unfortunately, the best I can give you as a server owner myself is the fact that my servers run the best (and I have full control over my server) when it's just a pure Forge environment.  I've got item restrictions, teleport commands, ranks, and everything you'd expect on a modern server these days running on just Forge.
