### ISSUE TITLE
[Feature Request] Colorblind options or optimization

### ISSUE THREAD

**Issue by animeartist88** [Draconic-Inc/Draconic-Evolution#1706]
Made a modpack (Minecraft ver 1.12.2) including DE (ver 2.3.27.353) and had a player complain that they can't read the amount of energy in their generator. [Screenshot.](https://media.discordapp.net/attachments/1062998386162270298/1068334903713861642/2023-01-27_01.00.28.png?width=1645&height=896)

Seeing their screenshot, I have to agree that the dark blue on black is really difficult to make out. It strains the eyes even with perfect color vision. If this is already fixable, I apologize for wasting your time, but I don't see a config file or any mod options in the in-game config to change this text color. Can we possibly get a patch to make it a little easier on those with colorblindness or weaker eyes? It doesn't have to be full customization, just changing the text color to a lighter one would work fine.

Thanks for your time!
~Anime

**Comment by brandon3055** [comment]
Try this.
https://ss.brandon3055.com/2be99
It *should* be compatible with the latest version already on curse.

**Comment by brandon3055** [comment]
Looks like the mob grinder and energy infuser have the same issue. This should fix those aswell.
[Draconic-Evolution-1.12.2-2.3.28-guifix2-universal.jar](https://ss.brandon3055.com/db4ca)

**Comment by animeartist88** [comment]
We'll try it right away! Thank you!

**Comment by animeartist88** [comment]
It's much better now! Many thanks from me and my struggling player! One question: will this GUI version need to be installed on the server as well, or can it have the regular 2.3.28 version and this can be client-side only?

**Comment by brandon3055** [comment]
It should *theoretically* work with the existing version.

**Comment by animeartist88** [comment]
Ahhh, I guess we'll wait till our next update is ready (later today) and find out then. I'll leave the ticket open and get back to you once we've tested the compatibility.

**Comment by animeartist88** [comment]
Update: It seems to be working fine! The server didn't reject me for having the wrong version, and the GUI color is the fixed version. Thank you so much for the super speedy solution!

**Comment by FoxMcloud5655** [comment]
Good mod dev, am I right?  ;)
