### ISSUE TITLE
[1.18] Dependencies not reported.

### ISSUE THREAD

**Issue by ShadwDrgn** [Draconic-Inc/Draconic-Evolution#1712]
## Base information
* Minecraft version: 1.18.2
* Mod version: 3.0.27.515
* Minecraft Forge version: 10.2.0
* Mod Pack: Kitchen Sink pack with minor config changes

### Crash report
https://pastebin.com/cB7DPsaT

### Description / steps to reproduce
Just launch minecraft Without codechickenlib and brandonscore. Bar loading gets to the end then crashes out. No notice of required mods is given.

**Comment by ShadwDrgn** [comment]
Therer was no 1.18 button so not sure if you're supporting it yet as it's so new, but i missed this mod so much so i'm hoping to get it running <3

**Comment by ShadwDrgn** [comment]
Looks like i  was missing brandon lib and codechicken lib. So the bug here is jsut that minecraft normally tells people when depenedencies are missing and which they need, but it did not in this case.

**Comment by brandon3055** [comment]
Its possible mixins are running before the normal mod dependency checks and my mixins were exploding due to missing CCL. I will have to look into this.

**Comment by SigmaFlame** [comment]
I have this problem too, trying to create my server's modpack.
Hope this bug will be fixed soon, we're waiting for that to launch our server.

But I know it's REALLY difficult to fix a bug, so good luck, we'll be patient.

**Comment by FoxMcloud5655** [comment]
As far as I know, the issue was resolved by adding Brandon's Core and CodeChickenLib.  If you're having an issue as well, please post the crash report.

**Comment by ShadwDrgn** [comment]
closing this so i'm not contributing to a messy issue list assuming it's not critical enough to fix w/e is making minecraft not report the missing dependency. Not to anyone finding this issue as a search that the above does in fact fix this.
