### ISSUE TITLE
[1.16] <Title>

### ISSUE THREAD

**Issue by stobinee** [Draconic-Inc/Draconic-Evolution#1714]
## Base information
* Minecraft version:1.16.5
* Mod version:3.0.27.462
* Minecraft Forge version:36.2.39
* Mod Pack: sky bees 2(curseforge)

### Crash report

[hs_err_pid2036.log](https://github.com/Draconic-Inc/Draconic-Evolution/files/10743917/hs_err_pid2036.log)

### Description / steps to reproduce
any pack with draconic evolution crashes with an identical error if I go into quests, items and items jei if the pack is without a draconic then it works perfectly

**Comment by GreatOrator** [comment]
You'll need to provide the actual minecraft forge crash logs, not the windows logs.

**Comment by brandon3055** [comment]
> You'll need to provide the actual minecraft forge crash logs, not the windows logs.
JVM crashes don't usually produce a regular crash report.

@stobinee Your best bet for now would be to disable all shaders in both the DE and BrandonsCore config files.
There are some issue with the 1.16 shaders when run on certain systems that i simply have not been able to figure out.

Fortunately, with vanillas new shader based rendering system, these issues should not be an issue in 1.18+.

**Comment by stobinee** [comment]
[latest.log](https://github.com/Draconic-Inc/Draconic-Evolution/files/10757197/latest.log)

**Comment by FoxMcloud5655** [comment]
Closing, as this is fixed in later Minecraft versions.
