### ISSUE TITLE
[1.18] Crash on launch with a large modpack

### ISSUE THREAD

**Issue by SigmaFlame** [Draconic-Inc/Draconic-Evolution#1717]
java.lang.IllegalArgumentException: Failed to create model for minecraft:pig

## Base information
* Minecraft version: 1.18.2
* Mod version: 3.0.28.516
* Minecraft Forge version: 40.2.1
* Mod Pack: N/A

### Crash report
https://pastebin.com/4Q4GQidW

### Mods list
https://pastebin.com/DrJCeH81

### Description / steps to reproduce
Trying to launch the game makes the game crashes on launch.
Removing Draconic Evolution fixes the issue and the game is not crashing.
Removing the mod inside the crash report (itshallnottick for this one) just makes that another mod will replace it.
It mentioned betteranimalsplus then twilightforest before, and now it's the turn of itshallnottick.
As you can see in my mods list, I do have Brandon's Core and CodeChickenLib.
Just Draconic Evolution alone is working. (alone but with its two dependencies though)

### Another important thing
Note that there is no 1.18 bug section in your github.

**Comment by danieluvv** [comment]
I had a similar problem with the render of weapons, and fixed it whit this. 

1. Open the folder AppData, then open the folder Roaming... and locate your Minecraft World Folder.
2. There, open the folder "config" and then, open the folder "brandon305".
3. Open with a notepad the file called "Draconic Evolution" and there, find this line of code "# These are client side config properties."
4. In this part: "# Set this to false to disable the fancy 3D tool models. (Requires restart)
	B:"fancyToolModels"=true", change "true" for "false".
5. Save the file and Re-open your world.

**Comment by FoxMcloud5655** [comment]
That's a completely separate issue that should have been fixed a long time ago now.

**Comment by DataDalton** [comment]
This might relate to #1722 where you need Brandon's Core 3.1.9+, whereas you have 3.1.8.277

**Comment by DataDalton** [comment]
~~This may be in reference to #1722 , you have Brandon's Core 3.1.8.277 and need 3.1.9+~~

I made a previous comment but realized it was inaccurate, I apologize for this as I did not see you say that Draconic Evolution works alone with its dependencies.

**Comment by mac124568** [comment]
I have encountered similar issues. It seems Draconic doesn't like interacting with mods with custom rendering engines, that is why it seems to work whenever you disable fancy weapon models.

**Comment by FoxMcloud5655** [comment]
1. I haven't seen this issue in my modpack with these same mods.
2. This issue is old.
3. This issue is for 1.18.2, which isn't being supported.
