### ISSUE TITLE
AOE module, no mining ores problem

### ISSUE THREAD

**Issue by KEJWII** [Draconic-Inc/Draconic-Evolution#1720]
Minecraft version: 1.12.2
Mod version: Draconic-Evolution-1.12-2.3.28.193
Minecraft Forge version: forge-1.12.2-14.23.5.2869
Modpack: SurviveTech 1.3

Problem info:

I ran into this problem using the fluorite pickaxe from the GemTools mod (ores from other mods were not mined)
I decided to start using tools from draconic evolution in the end of the game hoping that Draconic Pickaxe will solve this problem... it turns out that this problem has not gone away, still ores from galacticraft mod are not mined using AOE, however, I noticed that if I mine the same ore next to the same ores, they are mined
I'll be glad if someone explains this problem and best of all knows the solution

vanilla ore mining works and I checked if it's not a question of mining speed. In creative mode there is no problem, only in survival mode (with commands disabled)
I edited the draconicpickminespeed values from 1 to 1000. Same result
I haven't tested spells yet
because the pickaxe you see in the picture was enchanted with several spells
advanced efficiency V
Luck III
e.t.c
but out of frustration I slowly removed all spells and use ftb quest to give myself draconic pickaxe max upgrade to test. Still the same effect

(It annoys me)
![Base Profile Screenshot 2023 02 25 - 21 04 58 33](https://user-images.githubusercontent.com/106697974/221377370-0e362934-e187-4365-aa8e-f01dcb6c0ace.png)

**Comment by FoxMcloud5655** [comment]
This is not a bug and not exclusive to Draconic Evolution's AOE mining; you'll see this happen with Tinker's Construct and many other mods.  The "required pickaxe level" needed to mine the ore is too high compared to the stone you're mining around it.  This is to prevent people from placing a single stone in the way, mining that, and getting an AOE mine of something much, much harder to get.  For instance, Obsidian.  If you were to mine End Stone near Obsidian, you'll see the same effect.

**Comment by KEJWII** [comment]
> This is not a bug and not exclusive to Draconic Evolution's AOE mining; you'll see this happen with Tinker's Construct and many other mods. The "required pickaxe level" needed to mine the ore is too high compared to the stone you're mining around it. This is to prevent people from placing a single stone in the way, mining that, and getting an AOE mine of something much, much harder to get. For instance, Obsidian. If you were to mine End Stone near Obsidian, you'll see the same effect.

Oh... sorry i forgot there is still this issue of the problem sooo is there any solution using a change in the config file?

**Comment by FoxMcloud5655** [comment]
No, you'd have to find a mod that overrides this default behavior for all mining tools, and I don't know of one personally.
