### ISSUE TITLE
[1.18.2] Crash on launch

### ISSUE THREAD

**Issue by NickyMB** [Draconic-Inc/Draconic-Evolution#1722]
During launching Minecraft (larger modpack) I have a crash error and prompt that I need brandonscore 3.1.9+
but there is no higher version than 3.1.8.278

**Comment by FoxMcloud5655** [comment]
This is correct.

**Comment by TheLMiffy1111** [comment]
The latest 1.18.2 version of BrandonsCore on CurseForge is 3.1.8.278, and 3.1.9.279 is not on CurseForge.

**Comment by DataDalton** [comment]
Looks like as of March 7, 2023, CurseForge has [Brandon's Core version 1.18.2 3.1.9+ ](https://www.curseforge.com/minecraft/mc-mods/brandons-core/files/all?filter-game-version=2020709689%3A9008)
