### ISSUE TITLE
[1.16.5] Wierdly holding tools when shaders are disabled

### ISSUE THREAD

**Issue by Lendoker** [Draconic-Inc/Draconic-Evolution#1723]
Draconic evolution bugs with my shaders turned on, so I set useShaders to false in config, but then realised that items are holding strangely

Version 1.16.5, latest draconic evolution version installed
![2023-03-03_00 40 28](https://user-images.githubusercontent.com/70807737/222576437-17add348-57ea-4ada-9884-2e29fa57d4e5.png)
![2023-03-03_00 42 57](https://user-images.githubusercontent.com/70807737/222576487-e2a68abe-8e93-4742-a639-dd815306c3f6.png)

**Comment by FoxMcloud5655** [comment]
If this issue is still happening in the 1.20.1 version of Draconic Evolution, please feel free to re-open this issue.
