### ISSUE TITLE
[1.16] Module disappearing

### ISSUE THREAD

**Issue by NeyTwix** [Draconic-Inc/Draconic-Evolution#1725]
## Base information
* Minecraft version: 1.16.5 
* Mod version: 3.0.27.462
* Minecraft Forge version: 36.2.39
* Mod Pack: 
https://pastebin.com/ZuTGYkbY

### Description / steps to reproduce

When we put modules in equipment such as the chestplate or sword, when we close the interface, they disappear.

**Comment by NeyTwix** [comment]
We don't have the permission to go in creative mode.

**Comment by FoxMcloud5655** [comment]
Unfortunately, the fact of the matter remains that it is a known issue and that it won't be fixed on 1.16.5.  Has something to do with capabilities not being supported in certain GUIs, and the most common one reported is the Creative Mode menu.

Modded containers can do this too if they aren't coded right, which is likely what you're seeing here.
