### ISSUE TITLE
[1.18] Shield not recharging 

### ISSUE THREAD

**Issue by Irongold51** [Draconic-Inc/Draconic-Evolution#1726]
## Base information
* Minecraft version:1.18.2
* Mod version:1.18.2-3.0.29.524-universal
* Minecraft Forge version: 40.1.2
* Mod Pack:

With chaotic large shield capacity the shield does not recharge I have not tested with the others but know a bug that must be fixed
thank you

**Comment by FoxMcloud5655** [comment]
All Large Shield Capacity Modules do not have any recharge by design.
