### ISSUE TITLE
[1.12] Draconic reactor Core falls Down

### ISSUE THREAD

**Issue by Swiffyshit** [Draconic-Inc/Draconic-Evolution#1728]
Draconic reactor Core Falls down And Rolls Away, game crashes when touching The Rolling Core

My Draconic reactor Core Sometimes Falls Down, When this Happens the Animation of The Stabilisers And Reactor Energy Injector Stops and The Core With the Shield Texture and Stuff Rolls away (Most of the Times to South east) and When i touch the Rolling Core Sometimes The Core Disappears and Then The Game Crashes (No crash report but a Exit Code that says -1073741819, Server doesnt crash) pls Fix it its Annoying...

**Comment by brandon3055** [comment]
I wouldn't worry about it. This is one of those odd transient bugs that for whatever reason only happens one day per year. Usually by the time I get around to looking at it, it has already fixed itself.

**Comment by Swiffyshit** [comment]
Funny enough with setting the Roller to null. Just set the system time to 3rd of April every time😂
