### ISSUE TITLE
[1.16] <Title>Crash after start (Mod cant be loaded)

### ISSUE THREAD

**Issue by SikiciBebek** [Draconic-Inc/Draconic-Evolution#1730]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.29.
* Minecraft Forge version: 36.2.39
* Mod Pack: (if applicable) Selfmade

### Crash report
... has failed to load correctly

### Description / steps to reproduce

Its a Modpack made by myself to play with some friends. Sadly it keeps crashing after i start.
Maybe u could help me with that ^^

Once you have the files please **DO NOT** copy their contents into this issue. 
Instead use a paste service to such as pastebin.com (Or what ever you prefer)

If you have never used pastebin before its pretty simple and does not require an account or anything.
Just go to pastebin.com,
Copy the *entire* contents of the crash report into the "New Paste" text box  
Then press "Create New Paste", This will create and open a new paste in your browser.
Now simply copy the URL from your browser and paste it into this issue.
-->https://pastebin.com/0tNQmLUF

**Comment by FoxMcloud5655** [comment]
This has absolutely nothing to do with Draconic Evolution.  Go get rid of or change the version of HammerLib you're using.  Also, RandomPatches has been known to crash you, so don't use that either if you can avoid it.

**Comment by SikiciBebek** [comment]
Okay ty ^^
