### ISSUE TITLE
[1.18]  crash on menu load

### ISSUE THREAD

**Issue by Xplodin** [Draconic-Inc/Draconic-Evolution#1732]
## Base information
* Minecraft version: 1.18
* Mod version: 1.18.2-3.0.29.524
* Minecraft Forge version: 40.2.1
* Mod Pack: (if applicable)
Beanpack refried. Updating its mods
### Crash report
(If applicable)

https://gist.github.com/Xplodin/207e6ebe041679b33469c8f38b7dcd13
### Description / steps to reproduce

 boot the game, when it gets to the main menu it crashes

**Comment by FoxMcloud5655** [comment]
This is almost definitely a mod conflict.  Try putting up the game with just Draconic Evolution and it's dependencies.  Once you've verified that works, add half your mods back and keep doing that until it crashes again.

**Comment by brandon3055** [comment]
This crash seems to be occurring on CCL's side, though I have no idea what could be causing it.
https://gist.github.com/Xplodin/207e6ebe041679b33469c8f38b7dcd13#file-gistfile1-txt-L471
That would be a question for @covers1624

**Comment by FoxMcloud5655** [comment]
Covers has opened an issue related to this on CCL's side.
https://github.com/TheCBProject/CodeChickenLib/issues/460
