### ISSUE TITLE
[1.18] Comma not appearing correctly using a russian OS

### ISSUE THREAD

**Issue by GinDoyr** [Draconic-Inc/Draconic-Evolution#1733]
Minecraft version: 1.18.2
Mod version: 3.0.29.524-universal
Minecraft Forge version: 40.2.1

Basically the same thing as #635, but on a newer version and a different language
![image](https://user-images.githubusercontent.com/109394929/233778476-4d399476-b0d0-460a-a899-240e52c78bd4.png)

**Comment by GinDoyr** [comment]
Updating Forge up to 40.2.2 doesn't help

**Comment by FoxMcloud5655** [comment]
Not something we can fix without having access to said Russian OS.  If you can fix up the .lang file and send a pull request, we'll happily review and approve it.

**Comment by FoxMcloud5655** [comment]
My apologies; this is an issue that is fixable.  Brandon will be working on this Soon:tm:.
