### ISSUE TITLE
[1.12] Armor is not displayed correctly

### ISSUE THREAD

**Issue by Alprazxlam** [Draconic-Inc/Draconic-Evolution#1738]
## Base information
* Minecraft version: 1.12.2
* Mod version:  2.3.2.28.354
* Minecraft Forge version:  14.23.5.2860
* Mod Pack: Custom

### Description / steps to reproduce

The armor from mode is displayed incorrectly, the versions of the associated mods are the latest. When starting Minecraft with only DE and related armor is displayed correctly. Installed mods and type of armor attached.
![изображение_2023-05-06_155921290](https://user-images.githubusercontent.com/132758079/236625669-4f4156c1-cf92-427b-a8cc-101993673da5.png)
![изображение_2023-05-06_155802897](https://user-images.githubusercontent.com/132758079/236625614-391a8063-a988-411b-b529-a250a412b9c4.png)
![изображение_2023-05-06_155949371](https://user-images.githubusercontent.com/132758079/236625692-92788689-29d7-4de6-a865-8aa82cbed5ac.png)
![изображение_2023-05-06_160109662](https://user-images.githubusercontent.com/132758079/236625789-a6aa664f-e9ef-4e3d-bdbc-920cd38a97ee.png)

**Comment by FoxMcloud5655** [comment]
First of all, this is not incorrect. These are the old textures, so the newer 3D models simply isn't being displayed either due to a config option or the models being disabled somehow.

Secondly, why OptiFine?  Please don't use that piece of garbage.  It messes with all the core rendering methods and replaces them with its own, causing completely unpredictable behavior in mods.

**Comment by Alprazxlam** [comment]
And what to use if not OptiFine? I don't know much about mods, so I don't mind hearing some really good advice about optimizing without it.

**Comment by FoxMcloud5655** [comment]
GitHub issues is not the place to ask for these kinds of things; you can join the "Brandon's Mods" discord if you want answers like this in the future.

With that being said, use Phosphor if you want lighting engine optimizations like what OptiFine provides without breaking mods.
