### ISSUE TITLE
[1.16] draconic evolution items kicking me of my server

### ISSUE THREAD

**Issue by TheAleatoryName** [Draconic-Inc/Draconic-Evolution#1739]
* Minecraft version: 1.16
* Mod version: any
* Minecraft Forge version: lastest

Hi ive been getting this error and ive been trying to find out why this happening i tried searching on internet and didnt found anything
this only happens when i put a draconic evolution item on my inventory/dropped the server kicks me doesnt matter if its a wyvern tool or an chaotic one the server lets me join normally without those items in my inventory 

![image (2)](https://user-images.githubusercontent.com/65627232/236922696-8d30c027-cfb0-4a2f-aa8e-eaead25f4978.png)

**Comment by FoxMcloud5655** [comment]
A version of Draconic Evolution does not exist for Minecraft version 1.16.  Minecraft Forge doesn't even exist for this version either, so I'm going to assume that you meant 1.16.5.

"Any" isn't a mod version.  I cannot assume what version you have, so you need to let us know.

"Latest" isn't a Minecraft Forge version.  The issue you're having doesn't seem like it matters what Forge version you have, so I'm just going to assume that you're using version 36.2.39.

Sounds to me like you need to update your version of Draconic Evolution.

**Comment by TheAleatoryName** [comment]
with any i wanted to mean any version of draconic evolution is giving me this exact problem i tried downgrading this mod but still got the same problem

**Comment by Andress-s** [comment]
I faced the same problem. Is there a solution?

**Comment by FoxMcloud5655** [comment]
> I faced the same problem. Is there a solution?Go look at #1826.

**Comment by Andress-s** [comment]
> > I faced the same problem. Is there a solution?
> 
> Go look at #1826.

So there is no solution to the problem? I don't see a solution to this problem in #1826. I get kicked off the server when I take tools/armor from Draconic Evolution into my inventory. I don't have Ice And Fire mods or FTB Chunks. Although I have an FTP Library, FTB Teams and FTB Quests. I'll try to turn them off. I will write about the result. If there are any more ideas, I would gladly try them to solve this error.

**Comment by Andress-s** [comment]
> > > I faced the same problem. Is there a solution?
> > 
> > 
> > Go look at #1826.
> 
> So there is no solution to the problem? I don't see a solution to this problem in #1826. I get kicked off the server when I take tools/armor from Draconic Evolution into my inventory. I don't have Ice And Fire mods or FTB Chunks. Although I have an FTP Library, FTB Teams and FTB Quests. I'll try to turn them off. I will write about the result. If there are any more ideas, I would gladly try them to solve this error.

No, it didn't turn out to be a solution. Everything is also not working.
![image](https://github.com/user-attachments/assets/8fcdfc9b-580e-46db-9b7c-a509852de4c5)

**Comment by FoxMcloud5655** [comment]
Your screenshot was the info needed to diagnose your problem.

1.16.5 isn't supported anymore and won't receive bug fixes.  Please update to a later version of Minecraft that's supported.  As of the time of this writing, 1.20.1 is the only version supported.

**Comment by Andress-s** [comment]
> Your screenshot was the info needed to diagnose your problem.
> 
> 1.16.5 isn't supported anymore and won't receive bug fixes. Please update to a later version of Minecraft that's supported. As of the time of this writing, 1.20.1 is the only version supported.

So of course I have version 1.16.5. I'm writing to the topic with version 1.16.5. It's a very strange decision to remove mod support from popular versions, even though they are already old. Many mod server players, especially in the CIS, love the old versions. This may come as a shock to you, but many still play on 1.7.10, 1.12.2. I personally keep my servers on 1.16.5, because there are many servers, cores and plugins here. I love this version. You also need to fix small but serious errors. I don't think this mistake is very big. I found a version of this mod very easily, which is fixed, albeit unofficially.
I wish you all to be well. Please consider supporting older versions. Many players really love these versions!
