### ISSUE TITLE
Custom Fusion recipes

### ISSUE THREAD

**Issue by Endo-Studios** [Draconic-Inc/Draconic-Evolution#1740]
I am currently developing a modpack for 1.18.2 called Chaotically Industrial. The premise is to become god with the chaotic chestpiece. I would like to change the recipe for the wyvern fusion craft, however there is not a guide within the config/brandon3055 folder. I have tried looking at other similar conficts resolved in the issues tab yet none are in or above 1.18.3 version. If I could get an explaination of how to properly do custom fusion crafting, that would be greatly appreciated.

**Comment by FoxMcloud5655** [comment]
In later versions of Minecraft, recipes have moved towards using datapacks.  This is also true for Draconic Evolution.  Open up the .jar as a .zip file (7-zip is your friend here) and look through the `data/draconicevolution/recipes/tools` folder for `chaotic_chestpiece.json`.  You can follow the format listed there.
