### ISSUE TITLE
[1.16] module config

### ISSUE THREAD

**Issue by mods-player** [Draconic-Inc/Draconic-Evolution#1742]
## Base information
* Minecraft launcher: Hello MineCraft Launcher!(HMCL)
* Minecraft version: 1.16.5
* Mod version: 3.0.29.518
* Minecraft Forge version: Forge-1.16.5-36.2.35
* Mod Pack: Based on the "**光芒消逝之日**"(mcmod.cn download) mod pack, but additional mods added
* But it does not affect the contents of the mod pack
* modList:
* ![Screenshot 2023-06-10 172339](https://github.com/Draconic-Inc/Draconic-Evolution/assets/96873869/41f95421-af18-41d7-afaa-ebb5a2410dce)
![Screenshot 2023-06-10 172404](https://github.com/Draconic-Inc/Draconic-Evolution/assets/96873869/1f4de93e-d48e-42bf-ab8c-173e8255e118)
![Screenshot 2023-06-10 172424](https://github.com/Draconic-Inc/Draconic-Evolution/assets/96873869/d251a702-b4fe-4bde-8423-49552554b97a)
![Screenshot 2023-06-10 172313](https://github.com/Draconic-Inc/Draconic-Evolution/assets/96873869/c43511d4-eb92-4bcc-b72b-da83a9190cff)

### Crash report
Not Crash, It Module config can't using bug

### Description / steps to reproduce

I changed "ModuleStats.cfg" and saved it, opened the game, only to find that the file was initialized and the data was not applied, I have ruled out reaching the upper limit of numbers, and this will not be the case with other configs. Here are the changes, after you start the game, and the logs

![Screenshot 2023-06-10 171243](https://github.com/Draconic-Inc/Draconic-Evolution/assets/96873869/fefeeb7e-8a20-4e1e-aeb5-6430cb038705)
![Screenshot 2023-06-10 171346](https://github.com/Draconic-Inc/Draconic-Evolution/assets/96873869/2493a6a1-9d54-439b-ac93-c521955a62c5)
log:
[minecraft-exported-logs-2023-06-10T17-13-58.log](https://github.com/Draconic-Inc/Draconic-Evolution/files/11712099/minecraft-exported-logs-2023-06-10T17-13-58.log)

**Comment by FoxMcloud5655** [comment]
You must set "override" to "true", otherwise, the values you enter will not be applied and will be reset to default.

**Comment by mods-player** [comment]
oh...ok thx :) 
I found the problem by the time I finished speaking, and I didn't have time to close it
