### ISSUE TITLE
[1.18] is crafttweaker implemented? no recipetype bracket found

### ISSUE THREAD

**Issue by Sethgno** [Draconic-Inc/Draconic-Evolution#1743]
Draconic-Evolution-1.18.2-3.0.29.524-universal.jar

\<recipetype:draconicevolution:fusion_crafting\> doesnt seem to exist. i see remnants of it in the main branch though.
i understand if its just not implemented yet since this is a recent port, im just making sure its not a bug.
k thanks for any info!

**Comment by FoxMcloud5655** [comment]
The author of CraftTweaker himself added support into Draconic Evolution.  Run the examples command using `/ct` to get an example script.

**Comment by Sethgno** [comment]
sorry i probably shouldve phrased this better.
using the crafttweaker command /ct dump_brackets should output all valid recipetypes.
<recipetype:draconicevolution:fusion_crafting> doesnt show up in the recipetype dump file.
using this recipetype returns an error.

but either way, if youre suggesting you have nothing to do with it then ill check with CT's devs

**Comment by FoxMcloud5655** [comment]
Technically yes, realistically, we don't have anything to do with it, but also no, since it requires integration in Draconic Evolution rather than CraftTweaker.  I'm going to reopen this issue and take a look at it.  I'll update you whenever I have more info.

**Comment by FoxMcloud5655** [comment]
Never did update you...  Well, since the release of DE on 1.20.1, CT support was temporarily removed as things have changed.  However, DE does use datapacks, and I've successfully added support for DE's Fusion Crafting Recipes within my own modpack, so it's 100% possible now.  The recipe type is registered.
