### ISSUE TITLE
[1.16.5] When I selec the armor my minecraft crash.

### ISSUE THREAD

**Issue by IGv350** [Draconic-Inc/Draconic-Evolution#1745]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.29.518-universal.jar
* Minecraft Forge version: 36.2.34
* Mod Pack: (if applicable)

### Crash report
Crash Report UUID: 8030cb0d-ace9-428d-81a8-3a90155e60b8

**Comment by FoxMcloud5655** [comment]
There's no crash report here, but turn off shaders in the config.  You have an AMD GPU, likely.
