### ISSUE TITLE
[1.16] Visual Bug - Tools & Armor

### ISSUE THREAD

**Issue by fluffy64** [Draconic-Inc/Draconic-Evolution#1746]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.29.518-universal
* Minecraft Forge version: 36.2.26
* Mod Pack: Maxandrekid

### Description / steps to reproduce

There are no icons of tools, weapons and armor (for example, in the inventory). Just a transparent icon where there should be some kind of tool. Although if, for example, you turn on the third-person view, and pick up any instrument, it will be visible in your hands. I can try to leave a link to all the mods, since the assembly is from the Russian creator, and is on Russian site.

![1](https://github.com/Draconic-Inc/Draconic-Evolution/assets/140315853/f28c4d59-a3a7-484c-8dff-f252756050e0)
![2](https://github.com/Draconic-Inc/Draconic-Evolution/assets/140315853/59eda6d6-56a9-48a7-b4b7-1ab8af6aeae3)
![3](https://github.com/Draconic-Inc/Draconic-Evolution/assets/140315853/55c6cf10-dfb0-4a77-a5cd-989379f6df9e)
![4](https://github.com/Draconic-Inc/Draconic-Evolution/assets/140315853/9c7014de-c50d-4745-8080-a3716fd29fb3)
![5](https://github.com/Draconic-Inc/Draconic-Evolution/assets/140315853/beb37502-dfe0-49af-9aa0-4375e7c58d47)

These are the screenshots where you can see my issue.

**Comment by FoxMcloud5655** [comment]
See, there's one small problem with all those screenshots.  You have shaders, and very likely are using OptiFine to do so.  Another big thing is that you're running on 1.16.5.

This is very much unsupported and will never be fixed because OptiFine is closed source.  If you absolutely must have shaders, use Rubidium and Oculus.

**Comment by msawatzky75** [comment]
I have this issue using rubidium, namely items within the inventory or in the world. it's also mentioned [here](https://github.com/Asek3/Rubidium/issues/424).
