### ISSUE TITLE
[1.12] <DE crashing>

### ISSUE THREAD

**Issue by Driaqz** [Draconic-Inc/Draconic-Evolution#1747]
Base information
* Minecraft version:1.12.2
* Mod version: 1.12.2
* Minecraft Forge version:1.12.2
* Mod Pack: Created by me

### Crash report https://pastebin.com/VQRZQdhN
Placing generator cause a crash and don't allow to entry the world because it causing crash again and again

**Comment by FoxMcloud5655** [comment]
If you put this together yourself, then it explains the reason why.

You didn't include all the required dependencies.  Go get the Redstone Flux API.
