### ISSUE TITLE
[1.16] Shields not registering

### ISSUE THREAD

**Issue by JeezyOG** [Draconic-Inc/Draconic-Evolution#1748]
## Base information
* Minecraft version: 1.16.5
* Mod version: 0.9.6
* Minecraft Forge version: 36.2.35/39
* Mod Pack: CrazyCraft Updated

### Description / steps to reproduce
Running into an issue where I made the draconic chest piece and put regular armor mods in it, at first it pulled power and had full shields, now no matter what it says no shields and doesn't register in combat. I've tried new chest pieces and all of them don't work and it stays saying no shields. No crash for the server and nothing showing the issue.

![shielderror](https://github.com/Draconic-Inc/Draconic-Evolution/assets/95136749/7553bec2-5d2d-4f11-b28d-60a0b07a3b29)
![shielderror2](https://github.com/Draconic-Inc/Draconic-Evolution/assets/95136749/c2f0e577-16f6-4963-ab1d-d16b27151e41)

**Comment by FoxMcloud5655** [comment]
Put a Shield Control Module in your Chest Piece.
