### ISSUE TITLE
[1.7.10] ru_RU.lang

### ISSUE THREAD

**Issue by MainPlay-TG** [Draconic-Inc/Draconic-Evolution#1750]
🇷🇺 Вижу на 1.7.10 нет русского языка, я сделал перевод с помощью Google переводчика и своего скрипта. Если нужен перевод на другие версии мода пишите мне в Telegram: [@MainPlay_YT](https://t.me/MainPlay_YT)
🇺🇲 I see there is no Russian language on 1.7.10, I made a translation using Google translator and my script. If you need a translation to other versions of the mod, write to me on Telegram: [@MainPlay_YT](https://t.me/MainPlay_YT)
[ru_RU.lang.zip](https://github.com/Draconic-Inc/Draconic-Evolution/files/12415204/ru_RU.lang.zip)

**Comment by MainPlay-YT** [comment]
🇷🇺 Случайно закрыл, я сейчас сижу на сайте с телефона
🇺🇲 Accidentally closed, I'm now sitting on the site from the phone

**Comment by MainPlay-YT** [comment]
🇷🇺 Ещё я перевёл manual.json, но не получается прикрепить файл
🇺🇲 I also translated manual.json, but I can't attach the file

**Comment by MainPlay-YT** [comment]
[manual-ru_RU.json.zip.gz](https://github.com/Draconic-Inc/Draconic-Evolution/files/12426283/manual-ru_RU.json.zip.gz)
🇷🇺 Загрузить обычный ZIP не получилось, для открытия файла надо распаковать этот GZ и потом в нём будет лежать ещё ZIP, а вот уже в ZIP архиве будет manual-ru_RU.json
🇺🇲 It was not possible to download a regular ZIP, to open the file you need to unpack this GZ and then it will contain another ZIP, but in the ZIP archive there will be manual-ru_RU.jsonIt was not possible to download a regular ZIP, to open the file you need to unpack this GZ and then it will contain another ZIP, but in the ZIP archive there will be manual-ru_RU.json

**Comment by FoxMcloud5655** [comment]
If you'd like to submit a translation, please open a pull request instead!
