### ISSUE TITLE
[1.16] <Cannot damage Chaos Guardian>

### ISSUE THREAD

**Issue by CornyIsmE0401** [Draconic-Inc/Draconic-Evolution#1751]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.29.518 - universal
* Minecraft Forge version: 36.2.34
* Mod Pack: Mystical Block

### Crash report
(If applicable)

### Description / steps to reproduce
I cannot kill Chaos though i destroy all crystal

**Comment by FoxMcloud5655** [comment]
Not a bug.  Be patient and keep hitting the guardian.  Get through its shield first, then you'll see the damage bar change.
