### ISSUE TITLE
[Feature Request] <Please port to 1.19.2)>

### ISSUE THREAD

**Issue by dfghfhdff** [Draconic-Inc/Draconic-Evolution#1752]
Please, port on a new versions (like 1.19 and mb 1.20)

**Comment by FoxMcloud5655** [comment]
Impossible until Code Chicken Library updates.

**Comment by FoxMcloud5655** [comment]
The plan is to skip 1.19.2 in favor of 1.20.1.  For more information, visit the Discord.
