### ISSUE TITLE
Add chaos crystals and everything that is with the boss chaos guardian.

### ISSUE THREAD

**Issue by Jgamingboy16** [Draconic-Inc/Draconic-Evolution#1753]
I played this mod a while ago and i found that i can get to the boss but when i kill it how do i respawn it back?
so i was wondering if you guys could implement the chaos type of blocks or anything that goes with the chaos dragon so i can fight it again and not trying to fight it in the end?

**Comment by FoxMcloud5655** [comment]
You don't respawn it again.  You find another island.  In single player, that won't be an issue.  On a multiplayer server, the End is typically reset regularly.  A command does exist to respawn the dragon, but it's for testing purposes only.
