### ISSUE TITLE
[1.16] Chaos guardian just kills himself with fireballs

### ISSUE THREAD

**Issue by roastpiece** [Draconic-Inc/Draconic-Evolution#1754]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.27.462
* Minecraft Forge version: 36.2.39
* Mod Pack: ATM6 1.8.28
Dedicated server with 150ms ping

### Description / steps to reproduce
Im not sure if its intended, but chaos guardian just kills him self with his explosions, which makes the fight trivial (assuming you don't die ;))
He damages him self both on shield and life hits.
Clip:
https://github.com/Draconic-Inc/Draconic-Evolution/assets/64126646/c0cea10d-ee02-4244-a8e8-64d4a4d74f33

**Comment by FoxMcloud5655** [comment]
No, it is not, but that looks like a mod conflict.  Besides, the 1.16.5  version is completely out of date right now and is unsupported.  If this was happening in 1.18.2, then we would look at it.
