### ISSUE TITLE
nedd help>

### ISSUE THREAD

**Issue by valounne** [Draconic-Inc/Draconic-Evolution#1755]
## Base information
* Minecraft version:1.16.5
* Mod version:-3.0.29.518
* Minecraft Forge version:idk
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce

yea so im trying to craft a pickaxe wont work and the armor dont exist

**Comment by FoxMcloud5655** [comment]
Too little info, no one else is having this problem.

Armor doesn't exist, go make the Chest Piece.  If you need help, go to the Discord.
