### ISSUE TITLE
[1.16.5] Chaos guardian 100% immortal.

### ISSUE THREAD

**Issue by TrueTheKiller** [Draconic-Inc/Draconic-Evolution#1757]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.59.518
* Minecraft Forge version: 36.2.34
* Mod Pack: Mystical Block

### Description / steps to reproduce
Not certain how to reproduce

The chaos guardian is comepletely immortal, i've already destroyed the crystals, and no matter what weapon i use it is still immortal, in the center it is meant to be immortal i am aware of that, but while flying around none of my weapons do any damage (draconic staff of power, draconic bow, red katar, tinkers sword, regular sword, etc.) Is this intended? If so what weapons deal damage, and if not is there any way to fix it? Another minor problem is that the redish fireballs it spews take around 600 shield away per hit.

**Comment by TrueTheKiller** [comment]
Forgot to meantion i changed the game difficulty from normal to hard midway through the fight, dont know if this caused the issue but incase it did i'm assing this here

**Comment by FoxMcloud5655** [comment]
The shield visually does not deplete, and the 1.16.5 version hasn't received any of the bug fixes that 1.18.2 has since it's not supported.

I suggest moving on to 1.18.2 or ignoring the visual bug and continuing to attack.
