### ISSUE TITLE
Is it normal for the 1.18.2 version of Guardian Crystal to be pushed by a piston?

### ISSUE THREAD

**Issue by AlanChrisa** [Draconic-Inc/Draconic-Evolution#1758]
Draconic-Evolution-1.18.2-3.0.30.529-universal

BrandonsCore-1.18.2-3.1.10.283-universal

CodeChicken Lib 1.18.2-4.1.4.488-universal

Minecraft：1.18.2

Forge：40.2.10

![1691305733_409479_Gkik](https://github.com/Draconic-Inc/Draconic-Evolution/assets/124572836/12f53420-5578-4876-9d89-488bb4c9ac0a)
![1691305734_409479_dxpt](https://github.com/Draconic-Inc/Draconic-Evolution/assets/124572836/26aeae59-9268-4c4d-9084-ceae1cb56f7b)

@FoxMcloud5655 
@brandon3055

**Comment by brandon3055** [comment]
That is a bug. 
Thank you for reporting it.
