### ISSUE TITLE
1.18.2 Cant use creative flight with the mod Deep Mob Learning: Reforged

### ISSUE THREAD

**Issue by Fluffy2211** [Draconic-Inc/Draconic-Evolution#1761]
Problem: 
When using key binding to fly nothing happens except fov changes for half a second and then reverts and doesn't allow flight with the flight module, power, and elytra disabled

Forge Version : 
40.2.10

Mods:
1. Deep Mob Learning: Reforged : dmlreforged-1.0.7.jar
2. CodeChicken Lib 1.8.+ : CodeChickenLib-1.18.2-4.1.4.488-universal.jar
3. Brandon's Core : BrandonsCore-1.18.2-3.1.10.283-universal.jar
4. Draconic Evolution : Draconic-Evolution-1.18.2-3.0.30.529-universal.jar

**Comment by brandon3055** [comment]
Deep Mob Learning most likely has its own flight mechanic that is interfering with DE's.
DE's flight is specifically implemented in a way that it should never interior with another mods flight. 

DE will only ever disable a player's flight if that flight was originally provided by DE,
I suspect DML's logic is simply, "Are we providing flight? No? Then disable the player's flight."
That logic works fine, if no other mods are attempting to provide flight.

**Comment by FoxMcloud5655** [comment]
Closing, as this issue is old now.
