### ISSUE TITLE
[1.12] <Title>JVM sometimes throws NullPointerException while entering the save with IntegratedDynamics

### ISSUE THREAD

**Issue by NEFirefox** [Draconic-Inc/Draconic-Evolution#1762]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.28.354-universal
* Minecraft Forge version:14.23.5.2860
* Mod Pack: (if applicable)

### Crash report
https://pastebin.com/pmFyLRxx
(If applicable)

### Description / steps to reproduce
1.try to enter some saves in the game
2.get crashed,*sometimes*
3.JVM throws NullPointerException
maybe IntegratedDynamics's TickHandler?
And the report point the bug to the DraconicChest.class and the brandonscore there

**Comment by FoxMcloud5655** [comment]
1.12.2 is not being supported anymore.
