### ISSUE TITLE
[1.18] Dislocators disappear when drop

### ISSUE THREAD

**Issue by CRiMX0N** [Draconic-Inc/Draconic-Evolution#1763]
Disappears when all Dislocators are droped regardless of Bound and Unbound.
Here is the list of Dislocators are facing this bug.

- Dislocator
- Dislocator (Player)
- Dislocator (Point to Point)
- Advanced Dislocator

**Comment by brandon3055** [comment]
Thank you.
Not sure how that managed to go unnoticed for so long, but I will try to release a fix later today.
