### ISSUE TITLE
[Feature Request] 1.19.2 support

### ISSUE THREAD

**Issue by nekohacker591** [Draconic-Inc/Draconic-Evolution#1764]
porting an older modpack for this version but draconic evolution does not support this version yet

**Comment by nekohacker591** [comment]
![image](https://github.com/Draconic-Inc/Draconic-Evolution/assets/73713314/6fe72ba2-15f6-402d-ac85-0ad6407ac24d)

code chicken was updated so its now possible

**Comment by FoxMcloud5655** [comment]
It'll be done when it gets done.  It's already in progress.
