### ISSUE TITLE
1.18.2 crash with codechicken lib

### ISSUE THREAD

**Issue by hyygybs** [Draconic-Inc/Draconic-Evolution#1768]
[crash-2023-12-16_17.42.53-client.txt](https://github.com/Draconic-Inc/Draconic-Evolution/files/13692112/crash-2023-12-16_17.42.53-client.txt)

**Comment by FoxMcloud5655** [comment]
If this is still happening on the 1.20.1 release, feel free to comment with another crash report and more details and we'll reopen the issue.
