### ISSUE TITLE
[Feature Request] <Title>  i have problem with Draconic-Evolution i get game crash

### ISSUE THREAD

**Issue by ahmad111bq** [Draconic-Inc/Draconic-Evolution#1769]
I have a problem that every time I open Minecraft with the Draconic mod, I get a game crash. I use an AMD card, but my friend has an Nvidia card and he has not had any problems? Is there a problem with amd or what?
![image](https://github.com/Draconic-Inc/Draconic-Evolution/assets/53987816/3fd41b72-5326-4bfa-9ff7-de8ca28f0c84)

**Comment by FoxMcloud5655** [comment]
AMD support was added mostly properly in 1.18.2.  If you're having issues launching Minecraft, make sure your driver's are up-to-date by going to AMD's website and installing the latest GPU drivers from there.
