### ISSUE TITLE
support 1.19 and 1.20

### ISSUE THREAD

**Issue by gjmhmm8** [Draconic-Inc/Draconic-Evolution#1773]
support 1.19 and 1.20

**Comment by brandon3055** [comment]
The current plan is to skip 1.19 and very few packs use 1.20 as it is almost identical to 1.20.1.
I am currently in the process of porting to 1.20.1, once that is complete the 1.20.2/3/4 ports will hopefully be relatively quick.

**Comment by enzofrnt** [comment]
> The current plan is to skip 1.19 and very few packs use 1.20 as it is almost identical to 1.20.1. I am currently in the process of porting to 1.20.1, once that is complete the 1.20.2/3/4 ports will hopefully be relatively quick.

Does it coming ?
