### ISSUE TITLE
[1.18] ComputerCraft causes game crash if energy ball is read/found on server unpause

### ISSUE THREAD

**Issue by Chaos02** [Draconic-Inc/Draconic-Evolution#1774]
## Base information
* Minecraft version: 1.18.2
* Mod version: 1.8.2-3.0.31.531
* Minecraft Forge version: 40.2.9
* Mod Pack: TechAttack v0.9.6-beta3 (on curseforge or my GitHub, I am the Author)

### Crash report
[crash-report.txt](https://pastebin.com/d0d634wz)
[debug.log before crash](https://pastebin.com/hHGXG8J6)

### Description / steps to reproduce
1. Set up [(wireless) Draconic evolution energy ball Monitor script](https://pastebin.com/axQJqYvT) in disk/startup.lua
2. Shutdown both CC Computers
3. stop MC server
4. start MC server again
5. server pauses after startup because nobody connected yet (using [Ready Player Fun](https://www.curseforge.com/minecraft/mc-mods/ready-player-fun))
6. connect to the server, game unpauses for a couple ticks
7. server crashes, same crash report every time.

ComputerCraft Discord is **absolutely positive** that the crash can only happen during CC compat with DE.

PS: sorry for the wrong label, you should add a 1.18 issue preset :P

**Comment by FoxMcloud5655** [comment]
Putting aside the fact that you run a bunch of client-side only mods on your dedicated server, have you tried reproducing this crash with just the affected mods?

**Comment by Chaos02** [comment]
I have not yet - I was also unaware that there were still client mods, I thought I removed all.

**Comment by FoxMcloud5655** [comment]
If you can get the crash to happen with just the affected mods, then one of us will look into it after the next release.

**Comment by FoxMcloud5655** [comment]
Closing as the release has happened and no further reports have been made on this issue.
