### ISSUE TITLE
[1.16] bag 3d items

### ISSUE THREAD

**Issue by Jawakun** [Draconic-Inc/Draconic-Evolution#1777]
Greetings. I'm trying to take an object from the creative, which are the 3D models that the client paints!
![Screenshot_2](https://github.com/Draconic-Inc/Draconic-Evolution/assets/119397023/bbfda96b-bbd5-44e2-ba5c-058762693ea0)

**Comment by coaber** [comment]
1.16 is deprecated unfortunately, it won't receive any more updates. make sure you've got tool shaders disabled in the mod config if you're using an AMD GPU though. Also, if by any chance you're using optifine, remove it.

**Comment by Jawakun** [comment]
All players have a problem with this problem

**Comment by FoxMcloud5655** [comment]
1.16.5 is unsupported.
