### ISSUE TITLE
draconic evolution 1.16.5

### ISSUE THREAD

**Issue by gawd4321** [Draconic-Inc/Draconic-Evolution#1778]
вылетает когда я захожу в инвентарь но в основном табе есть меч и кирка виверны также на меня надето нагрудник виверны ( наверное из за нагрудника ) перезагружать компьютер пытался и драйвера обновлял и откатывал

**Comment by FoxMcloud5655** [comment]
1.16.5 isn't supported anymore.  Turn off tool shaders in the config for Draconic Evolution.

**Comment by gawd4321** [comment]
не работает

**Comment by gawd4321** [comment]
в папку draconicevolution.cfg на строке isables the 3D tool and armor models. This is required if you want to use a 2D resource pack.
    B:disable3DModels=true
написал true так как стояло false

**Comment by FoxMcloud5655** [comment]
I did not tell you to turn off the 3D models.  I told you to turn off the tool shaders.
