### ISSUE TITLE
[1.16] < Crash when i search '@draconic' in JEI >

### ISSUE THREAD

**Issue by WayanD157** [Draconic-Inc/Draconic-Evolution#1779]
## Base information
* Minecraft version: 1.16.5
* Mod version: Last Version ( Draconic-Evolution-1.16.5-3.0.29.518-universal )
* Minecraft Forge version: 36.2.34
* Mod Pack: (Mine -  I didn't edit the mods or anything, I just downloaded them and put them in the mods folder)

### Crash report

https://pastebin.com/KkmKJHNw

**Comment by FoxMcloud5655** [comment]
Duplicate of #1597.
