### ISSUE TITLE
[1.20.1] Items Not rendered 

### ISSUE THREAD

**Issue by MrEizy** [Draconic-Inc/Draconic-Evolution#1786]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.1.565
* Minecraft Forge version: 47.2.0
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce
Well It just wont render items in first person its fine if they are thrown on the ground or viewed in f5 or by a another playing it wont show it. it will just be invisible

**Comment by FoxMcloud5655** [comment]
Not an issue with Draconic Evolution.  You likely have Rubidium or Embeddium installed.  Report the issue there.
