### ISSUE TITLE
[1.16] Game still crashing after the supposed fix

### ISSUE THREAD

**Issue by goncaloaa** [Draconic-Inc/Draconic-Evolution#1788]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.29.528 
* Minecraft Forge version: 36.2.42
* Mod Pack: My own

### Crash report
I dont think it made a crash report, this was the only file i found https://hastebin.skyra.pw/gunaquvako.bash

### Description / steps to reproduce
 Yesterday I posted here about a bug regarding the render of the armor crashing my game, it was deleted because it was a duplicate, I went to the issue that was the same as mine and did what was described there to fix it, it worked and I was able to play but today I opened the game to play with my friend and the issue came back, when he got near me with his armor I crashed.
I looked at the config files and the shaders were still disabled.
Please help

**Comment by FoxMcloud5655** [comment]
Draconic Evolution for 1.16.5 is unsupported.  Update to the 1.20.1 version of Draconic Evolution which already contains the fix for this issue.

**Comment by goncaloaa** [comment]
Ok thank you, I didnt know that 1.16.5 is unsupported, when I went to the issues page it only says that pre 1.12 versions are unsupported.
