### ISSUE TITLE
[1.20.1] <Title> 4000 us/t with draconic armor in chestplate slot

### ISSUE THREAD

**Issue by TheNamesJosh** [Draconic-Inc/Draconic-Evolution#1791]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.571
* Minecraft Forge version: 47.2.20
* Mod Pack: (if applicable) ATM9 TTS

### Crash report
(If applicable)

### Description / steps to reproduce

Putting a draconic chest plate in your chest slot instead of a curio with an assortment of modules will raise your tick rate up to 4000 us/t

**Comment by FoxMcloud5655** [comment]
It varies a lot from just simply 4K microseconds per tick, but it's certainly more laggy when placed in the chest slot vs. in the body slot of the Curios inventory.  My testing was with many modules, but the shield control module was the only one that significantly affected the TPS.

**Comment by FoxMcloud5655** [comment]
Okay!  So, after a going through a couple rounds of testing, the results are in.  Observable doesn't seem to count Curios correctly when it shows how much lag an entity is generating.  Spark tells the full story, and in both instances, they generated roughly the same amount of lag when the item stack was ticked.

This issue will be safely closed, and hopefully this helps everyone understand what's going on.
