### ISSUE TITLE
[1.20.1] Crash when mob grinder kills shulkers

### ISSUE THREAD

**Issue by LeoTorresGon** [Draconic-Inc/Draconic-Evolution#1792]
## Base information
* Minecraft version: 1.20.1
* Mod version :3.1.2.571
* Minecraft Forge version: 47.2.20
* Mod Pack: ATM 9 To The Sky (V1.0.5)

### Crash report
[Crash Log](https://pastebin.com/raw/ZdsbNtHA)

### Description / steps to reproduce
When using a mob grinder to kill a shulker, the game crashes. The crash report says it could also be Oculus or Embeddium, but the crash persists even without those.

**Comment by FoxMcloud5655** [comment]
Can confirm, this issue does still persist.

**Comment by brandon3055** [comment]
This should be fixed in the next release.
