### ISSUE TITLE
[1.16] "Place item in world" feature doesn't work properly on server

### ISSUE THREAD

**Issue by Neythi** [Draconic-Inc/Draconic-Evolution#1793]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.28.500
* Minecraft Forge version: 36.2.39
* Mod Pack: Chroma Sky 2 (1.0.9)

### Description / steps to reproduce

If I place one item on the wall, everything works fine. But if I place 2 or more items on the wall, they can no longer be right clicked. But it is necessary to break the whole frame of items _(in singleplayer everything works)_. Is there any solution to solve this problem?

Thank you in advance for your reply :)

**Comment by FoxMcloud5655** [comment]
The 1.16.5 version of Draconic Evolution is not supported.
