### ISSUE TITLE
[1.20.1] weapons don't render in third person or in multiplayer only in first person

### ISSUE THREAD

**Issue by Alex-Purschwitz** [Draconic-Inc/Draconic-Evolution#1794]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.575 and .571
* Minecraft Forge version: 41.2.20
* Mod Pack: (if applicable) All the mods 9 to the sky

### Crash report
(If applicable)

### Description / steps to reproduce

The weapons don't render in third person or in multiplayer only in first person. I've tried it in a single player world and in a server.

**Comment by FoxMcloud5655** [comment]
This is not an issue with Draconic Evolution.  Remove Embeddium/Rubidium or ask them to fix this issue.
