### ISSUE TITLE
[1.20.1] [Crash]: Armor piercing when using something like dodge from apotheosis, will lead to a loop and eventual crash

### ISSUE THREAD

**Issue by Satherov** [Draconic-Inc/Draconic-Evolution#1797]
## Base information
* Minecraft version: 1.20.1
* Mod version: 
* Minecraft Forge version: Draconic Evolution 1.20.1-3.1.2.575
* Mod Pack: ATM9: To the sky

### Crash report
You have to manually kill the instance since it’s trapped in a loop

Log: https://gist.github.com/Satherov/0545a25968bf6f87357dd6692cd1906c

### Description / steps to reproduce

- get a second player or entity
- Give said player / entity an armor pice or shield with a gem from apotheosis that sometimes causes dodge 
- get a bow with an piercing upgrade
- Shoot the player / entity until the dodge triggers
- The game will freeze

### Additional Information

I mentioned this originally in the apotheosis repository, but it seems to be a problem unique to Draconic Evolution‘s way of handling armor piercing.

https://github.com/Shadows-of-Fire/Apotheosis/issues/1276

Apparently Draconic Evolution uses a different way of handling armor piercings than other projectiles do, which is why this issue occurs.

**Comment by FoxMcloud5655** [comment]
This sounds like an issue that Apotheosis should fix, as they're the ones that implement the dodging.

**Comment by FoxMcloud5655** [comment]
Accidentally closed, will leave it to @brandon3055.

**Comment by brandon3055** [comment]
Hmm... Either I did something very dumb, or that code was broken at the time I copy-pasted it from forge. 

Will be fixed in the next release.
