### ISSUE TITLE
[1.20.1] Cores are missing when creating a spawner

### ISSUE THREAD

**Issue by TleyVi** [Draconic-Inc/Draconic-Evolution#1800]
## Base information
* Minecraft version: 1.20.1
* Mod version: 1.20.1-3.1.2.575
* Minecraft Forge version: 47.1.106

### Description / steps to reproduce

If you create a stabilized spawner with a wyvern core or higher, the spawner will be with a dragon core when dropped

https://youtu.be/Wrzb0MCEnn4

**Comment by FoxMcloud5655** [comment]
For clarification, the issue lies with capturing a Mob Spawner with a Wyvern Core or higher.  The resulting Stabilized Spawner will contain a Draconium Core.

**Comment by brandon3055** [comment]
Will be fixed in the next release.
