### ISSUE TITLE
[1.20.1] [Crash] Crash when putting Draconic Staff into Smithing Table (ATM9 Sky)

### ISSUE THREAD

**Issue by EndDragon438** [Draconic-Inc/Draconic-Evolution#1801]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.571
* Minecraft Forge version: 47.2.20
* Mod Pack: All The Mods 9: To The Sky

### Crash report
[(pastebin link (ATM9Sky))](https://pastebin.com/9xt2GUN3)

### Description / steps to reproduce

1: Get a Draconic Staff (Possibly another staff, untested)
2: Place it (I used quick move with Shift+LMB) into a Smithing Table (Specifically trying to work with Apotheosis in ATM9Sky)
3: Crash!

After testing this in a pack with ONLY DE, it seems to be caused by another mod (possibly Apotheosis) forcing the staff to be able to be input into a Smithing Table as this is not default DE behaviour.
This behaviour is consistent within ATM9Sky, and happens every time I put the staff into a Smithing Table.

If this issue is caused by another mod lemme know and I'll move it over to their source, or just the ATM devs if it's something with the actual pack.

**Comment by FoxMcloud5655** [comment]
Sounds like an Apotheosis issue, as they're the ones modifying how DE's item works.  Try removing Fast Suite and see if the issue persists before moving the issue to Apotheosis.
