### ISSUE TITLE
[Feature Request] <Adding some kind of upgrade template / tier installers>

### ISSUE THREAD

**Issue by xXseesXx** [Draconic-Inc/Draconic-Evolution#1803]
it would be nice if there was a way to craft an upgrade/ tier installer of sorts that allows me to upgrade my tools all in one go, this would feel so much better with autocrafting in mind. i suggest a upgrade template that costs a vanilla smithing template for netherite instead of the tool and doesnt include the energy controller, the energy controller will then be used like a netherite ingot with the new template in the smithing table

**Comment by FoxMcloud5655** [comment]
Due to different tools costing differing amounts of items, this request is impossible to fulfill.  You would have to make your own addon mod to implement this.
