### ISSUE TITLE
[1.20.1] <dupe module>

### ISSUE THREAD

**Issue by Mifr1l3551** [Draconic-Inc/Draconic-Evolution#1806]
## Base information
* Minecraft version: 1.20.1
* Mod version: (3.1.0-test-2.9999) 
* Minecraft Forge version: 47.2.1
* Mod Pack: (if applicable)

Dupe using any item that supports the module. It is necessary to open the module settings menu and throw the item into this moent, then pick up the modules. Modules will remain in the raised item.

https://youtu.be/6A1Oz4uyJDo

**Comment by brandon3055** [comment]
This is now fixed
