### ISSUE TITLE
[1.20.1] Tools not showing on hotbar

### ISSUE THREAD

**Issue by ObsidianProductions** [Draconic-Inc/Draconic-Evolution#1816]
## Base information
* Minecraft version: 1.20.1
* Mod version: Draconic-Evolution-1.20.1-3.1.2.583-universal
* Minecraft Forge version: 47.3.0
* Mod Pack: (if applicable)

After experiencing issues with Draconic Items not rendering as a result of having Oculus and Embeddium installed, I removed these mods and now the items are displaying correctly.
However, all draconic tools and weapons (Pickaxe, Sword etc) do not appear on my hotbar even though they appear within my inventory fine.

See attached my modlist.

[list.txt](https://github.com/user-attachments/files/16404780/list.txt)

**Comment by FoxMcloud5655** [comment]
Remove ImmediatelyFast.
