### ISSUE TITLE
[1.20.1] Rendering just breaks for certain items

### ISSUE THREAD

**Issue by Snowywasbanned** [Draconic-Inc/Draconic-Evolution#1818]
## Base information
* Minecraft version: 1.20.1
* Mod version:latest for 1.20.1
* Minecraft Forge version: modrinth wont let me see but it's stable one
* Mod Pack: [download](https://cdn.discordapp.com/attachments/475261367172071424/1267805562515488788/idkwhatnametoputforthemodpack_1.0.0.mrpack)

### Crash report
havent crashed, i can upload the log [download](https://cdn.discordapp.com/attachments/475261367172071424/1267879785774841956/message.txt?ex=66ab0d50&is=66a9bbd0&hm=7b24303b0fc7612aee682f638fdcc30dfae33a2c84677ee4c2c69da353ee4cf1&)

### Description / steps to reproduce
launch minecraft, load a world, and yeah
![bruh](https://github.com/user-attachments/assets/59e6a631-5f06-4c73-90c1-dfd7ce12657a)

**Comment by FoxMcloud5655** [comment]
First, never post "latest" as your version number.  We need exact versions to know exactly what's going on and if it's been fixed yet.

Second, your link to download the modpack is broken.

Third, you asked for help in the Discord and never followed any of my instructions for how to attempt fixing the issue you're having.  NEVER mix Fabric and Forge mods together if you want official support.

Finally, you always need to narrow down the mods involved to the minimum required to reproduce the issue consistently.
