### ISSUE TITLE
[1.20.1] Draconium don't SPawn

### ISSUE THREAD

**Issue by Untek** [Draconic-Inc/Draconic-Evolution#1823]
* Minecraft version: 1.20.1
* Mod version: Draconic-Evolution-1.20.1-3.1.2.583-universal
* Minecraft Forge version:  1.20.1-forge-47.3.0
* Mod Pack: (if applicable) BM REVELATION II
[Draconic.txt](https://github.com/user-attachments/files/16533276/Draconic.txt)

Hello

After a few days of looking for draconium I didn't find any so I installed an X ray mod to see if there was a bug and I noticed that there is no mineral in the overworld, low, end 
I don't have anything special in the config folder that would make the draconium ore disappear.

**Comment by Leonniclass** [comment]
That is not a bug by Draconic,
Draconium Ore only spawns in the otherside dimension in BM: Revelations II and BM: Exosphere
