### ISSUE TITLE
[1.20.1] Energy Core Visual Issue with Shaders

### ISSUE THREAD

**Issue by pangowo** [Draconic-Inc/Draconic-Evolution#1829]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.583
* Minecraft Forge version: 47.2.20
* Mod Pack: All the Mods 9 - To the Sky

### Description / steps to reproduce
When enabling a shaderpack the Energy Core visuals look bugged.
I tried it with the built-in ComplementaryUnbound (the attached image shows this one) and BSL 8.3 which looks really similar. 
I also tried disabling shaders in the de config which didn't change anything and without the shaders everything looks normal.

![de energy core](https://github.com/user-attachments/assets/ca86b699-9e94-4a21-b4f6-1c09986cda43)

**Comment by FoxMcloud5655** [comment]
This is not an issue with Draconic Evolution.  Take it up with Oculus.
