### ISSUE TITLE
[1.16] Buttons inside buildings dont work on local server

### ISSUE THREAD

**Issue by TottalyStupid** [Draconic-Inc/Draconic-Evolution#1830]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.29.518-universal
* Minecraft Forge version: 36.2.42

### Description / steps to reproduce

when i place the mob grinder or something else i press buttons in the menu and nothing happens, also works to the fusion crafter, on the local server of my friend, in singleplayer works fine

**Comment by FoxMcloud5655** [comment]
Draconic Evolution for Minecraft version 1.16.5 is no longer supported.
