### ISSUE TITLE
[1.20.1] External mods such as RFTools cannot read energy core values

### ISSUE THREAD

**Issue by BowBoy1** [Draconic-Inc/Draconic-Evolution#1831]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.583
* Minecraft Forge version: 47.3.0
* Mod Pack: Project Architect 2 (version 3.3)
### Description / steps to reproduce

Setting up an Energy Core (in my case, a tier 8) and attempting to read its values with mods like RFtools using the screens does not work, as you can only link the screens to the energy pylons and the value display options will pull from the pylon rather than the energy core. Marking as a bug because supposedly this was a thing you could do in prior versions.

**Comment by FoxMcloud5655** [comment]
Previous versions didn't have infinite energy.  It would need to be passed along as a string to be decoded into a number on the other end.

In fact, the recent CC integration pull request that was accepted very likely does this.  I haven't actually checked, but that would be the only way to get an accurate number.  This would need to be supported on the other end, not by DE.
