### ISSUE TITLE
[1.20.1] Crystals and other tools nor rendering with Complementary Shader

### ISSUE THREAD

**Issue by LucyDemooon** [Draconic-Inc/Draconic-Evolution#1833]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.583
* Minecraft Forge version: 47.2.20
* Mod Pack: (if applicable) ATM9 v0.3.0
* Shader: ComplementaryReimagined_r5.2.2

### Crash report
no crash

### Description / steps to reproduce

Crystals and other tools nor rendering with Complementary Shader
![2024-09-03_00 59 45_2](https://github.com/user-attachments/assets/72dc0177-623c-4754-bc55-420789287316)

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by FoxMcloud5655** [comment]
Not an issue with Draconic Evolution.  Take it up with Oculus.
