### ISSUE TITLE
[1.20.1] Opening Energy Core crashes client Instance

### ISSUE THREAD

**Issue by Veniak** [Draconic-Inc/Draconic-Evolution#1834]
## Base information
* Minecraft version: 1.20.1
* Mod version: Draconic-Evolution-1.20.1-3.1.2.583-universal
* Minecraft Forge version: 47.2.20
* Mod Pack: ATM 9 (to the Sky)

### Crash report

https://pastebin.com/2gqHUD8x

### Description / steps to reproduce

1. Build a Draconic Energy Core (The big storage one)
2. Open the gui
3. Adjust the max displayed Energy (visual only) to some decimal close to 0 (e.g. `0.3`)

I assume the issue is entering a valid float which is greater than 0 which later gets converted to a integer and leads to divide by zero.

**Comment by brandon3055** [comment]
This should be resolved in the altlatest version of DE
