### ISSUE TITLE
[1.20.1] Game crashes on startup - randomly 

### ISSUE THREAD

**Issue by muggleorwizard** [Draconic-Inc/Draconic-Evolution#1838]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.588
* Minecraft Forge version: 47.3.10
* Mod Pack: https://www.curseforge.com/minecraft/modpacks/ozone-skyblock-reborn (note: I develop this modpack, I have not had this issue but multiple players have had it)

### Crash report
java.lang.IllegalStateException: Failed to create model for draconicevolution:potentiometer

https://pastebin.com/xbD1sju2

[crash-2024-09-17_17.05.39-client.txt](https://github.com/user-attachments/files/17030955/crash-2024-09-17_17.05.39-client.txt)

### Description / steps to reproduce
Install modpack and launch. This crash only happens some of the time.

**Comment by FoxMcloud5655** [comment]
Covers has opened an issue related to this on CCL's side.
https://github.com/TheCBProject/CodeChickenLib/issues/460

**Comment by muggleorwizard** [comment]
Thanks, I'll follow up with them over there.
