### ISSUE TITLE
[1.12] <Title> Server crash on interaction with Draconic Evolution

### ISSUE THREAD

**Issue by Billy1020HD** [Draconic-Inc/Draconic-Evolution#1839]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.28.354(Draconic Evolution), 2.4.20.162(BrandonsCore)
* Minecraft Forge version: 14.23.5.2860
* Mod Pack: Infinity Evolved Reloaded

### Crash report
https://pastebin.com/ZRXkzjVp

### Description / steps to reproduce
 
I built the Energy Infuser and placed it.
I gave it energy and clicked on it.
Server crashed instantly.
The same with any block of this mod.

**Comment by FoxMcloud5655** [comment]
1.2.2 is no longer supported.
