### ISSUE TITLE
[1.20.1] Problem with equipment display

### ISSUE THREAD

**Issue by FilimonEnc** [Draconic-Inc/Draconic-Evolution#1842]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.588
* Minecraft Forge version: 47.2.20
* Mod Pack: (if applicable) ATM9 To The Sky

### Description / steps to reproduce

There is a problem with the display of equipment. when you play online, other players do not see your equipment, and if you throw a bow or pickaxe on the ground, they are invisible even to you

**Comment by FoxMcloud5655** [comment]
First, are you using any kind of external shaders?  If so, uninstall Oculus.

Second, are you running any mods that change rendering like Optifine or Rubidium?  Replace them with Embeddium.

Finally, are you using Forge or NeoForge?

**Comment by TGG88** [comment]
Me and my friends have the same problem,
we downloaded all the mods 9 were like it since we downloaded
we are using no shaders and are using forge

**Comment by FoxMcloud5655** [comment]
"Using no shaders" and "Uninstall Oculus" are two very different things.  Please actually try uninstalling Oculus from the modpack and watch your problems vanish.

There's a reason why I've always disliked All The Mods.

**Comment by TGG88** [comment]
> "Using no shaders" and "Uninstall Oculus" are two very different things. Please actually try uninstalling Oculus from the modpack and watch your problems vanish.
> 
> There's a reason why I've always disliked All The Mods.

THANK YOU
im a pretty newbie modder and this worked flawlessly

**Comment by 2econd17** [comment]
Hello, what is Oculus and how to remove it, well, that is, how to do what you say?
I have the same problem, but I don't understand how to solve it

**Comment by Krzykarek** [comment]
> Hello, what is Oculus and how to remove it, well, that is, how to do what you say? I have the same problem, but I don't understand how to solve it

A minecraft mod lol
