### ISSUE TITLE
wyvern or dragon AOE module

### ISSUE THREAD

**Issue by q2we6** [Draconic-Inc/Draconic-Evolution#1847]
Why does the pickaxe dig slowly after installing a wyvern or dragon AOE module? 3x3 module digs fast, but 5x5 and 7x7 dig very slowly even with enchantments and speed modules. Is this some kind of bug or is it supposed to be like that?

**Comment by FoxMcloud5655** [comment]
The more blocks you mine, the slower you break the entire thing.  Install Speed modules and make sure your config is set to mine at full speed.
