### ISSUE TITLE
[1.20.1] Advanced Dislocator Bugging in Choas Guardian fight

### ISSUE THREAD

**Issue by notsome1else** [Draconic-Inc/Draconic-Evolution#1853]
## Base information
* Minecraft version:
1.20.1
* Mod version:
* 3.1.2.588
* Minecraft Forge version:
47.3.0
* Mod Pack: (if applicable)
ATM9 - No Frills
### Description / steps to reproduce

I have set a teleporter point outside the Chaos Island in the End in the Advanced Dislocator trying to fight the Chaos Guardian
The first time after setting that point the teleportation works fine, the times after that i just dont get teleported or get teleported for a microsec and instantly teleported back. 
In the overworld or generally normal scenarios it works fine just in the chaos guardian fight it seems very buggy. Also the Blink mode does not get me out of the suction area of the Chaos Guardion

**Comment by FoxMcloud5655** [comment]
Literally all of what you just described is intended behavior.  During the boss fight, you are not supposed to leave.  The only thing that you can do to leave is to teleport outside of the dimension.  Any attempts to go outside of the island will pull you back to the center.
